#!/usr/bin/env -S deno run --allow-read --allow-write
//
// Turn a reference tree written by `tools/impact-reference.sh --impl ts` into
// the committed fixture `tests/data/impact-expected.json`.
//
// The fixture is what makes `cargo test` mean something on a machine that does
// not have the base IR or the page trees: the numbers and digests below are the
// frozen prototype's answers, so a port that drifts fails even where the corpus
// test skips. With the corpus present the same test regenerates every file and
// compares it against these numbers.
//
// **Nothing is substituted here** beyond two normalisations that are forced,
// both of which are paths and neither of which is an answer:
//
//   * the summaries' `ir` / `pages` fields, which name the directory the run was
//     given (`<IR>` / `<OUT>`);
//   * `totalSeconds`, dropped — it is wall clock.
//
// Everything else is the prototype's bytes.
//
// usage: gen-impact-expected.ts [--ref DIR] [--out FILE] [--base-ir DIR]

const argv = Deno.args.slice();
const opt = (name: string, dflt: string) => {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : dflt;
};

const REF = opt("--ref", "/private/tmp/lean-doc-relay/m3c/ref");
const BASE_IR = opt("--base-ir", "/private/tmp/lean-doc-relay/w7h/base-ir");
const OUT = opt(
  "--out",
  new URL("../data/impact-expected.json", import.meta.url).pathname,
);

/** FNV-1a 64, the same digest the M1/M2/M3-a/M3-b fixtures use. */
function fnv1a64(bytes: Uint8Array): string {
  let hash = 0xcbf29ce484222325n;
  for (const byte of bytes) {
    hash = BigInt.asUintN(64, (hash ^ BigInt(byte)) * 0x100000001b3n);
  }
  return hash.toString(16).padStart(16, "0");
}

function maybeRecord(path: string): { bytes: number; fnv1a64: string } | null {
  let raw: Uint8Array;
  try {
    raw = Deno.readFileSync(path);
  } catch {
    return null;
  }
  return { bytes: raw.length, fnv1a64: fnv1a64(raw) };
}

function text(path: string): string | null {
  try {
    return Deno.readTextFileSync(path);
  } catch {
    return null;
  }
}

function status(name: string): number {
  return Number(Deno.readTextFileSync(`${REF}/${name}-status.txt`).trim());
}

function complained(name: string): boolean {
  return Deno.readTextFileSync(`${REF}/${name}-complained.txt`).trim() === "yes";
}

/** The summary as the test will compare it: paths normalised, clock dropped. */
function summary(
  path: string,
  key: string,
  mask: string,
  // deno-lint-ignore no-explicit-any
): Record<string, any> | null {
  const raw = text(path);
  if (raw === null) return null;
  const value = JSON.parse(raw);
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(value)) {
    if (k.endsWith("Seconds")) continue;
    out[k] = k === key ? mask : v;
  }
  return out;
}

const IMPACT = [
  "census",
  "self",
  "referrers",
  "importers",
  "default-mode",
  "all-empty",
  "all-changed",
  "leaf",
  "multi",
  "file-only",
  "empty-file",
  "empty-file-all",
  "unknown-mode-quiet",
  "unknown-mode",
  "not-a-module",
  "no-ir",
  "census-and-set",
  "dup-changed",
];

const PRUNE = [
  "dry-remove",
  "real-remove",
  "orphans-site",
  "orphans-pages",
  "orphans-only",
  "cascade",
  "already-absent",
  "rerun-1",
  "rerun-2",
  "no-list",
  "no-pages",
];

// deno-lint-ignore no-explicit-any
const impact: Record<string, any> = {};
for (const name of IMPACT) {
  const setPath = `${REF}/${name}-set.txt`;
  const exists = text(`${REF}/${name}-printset-exists.txt`);
  impact[name] = {
    status: status(name),
    complained: complained(name),
    printSetAsked: exists !== null,
    printSetExists: exists === null ? null : exists.trim() === "yes",
    printSet: maybeRecord(setPath),
    census: maybeRecord(`${REF}/${name}-census.tsv`),
    summary: summary(`${REF}/${name}-impact.json`, "ir", "<IR>"),
  };
}

// deno-lint-ignore no-explicit-any
const prune: Record<string, any> = {};
for (const name of PRUNE) {
  const files = text(`${REF}/${name}-files.txt`);
  const dirs = text(`${REF}/${name}-dirs.txt`);
  const count = (body: string | null) =>
    body === null ? null : body === "" ? 0 : body.trimEnd().split("\n").length;
  prune[name] = {
    status: status(name),
    complained: complained(name),
    summary: summary(`${REF}/${name}-prune.json`, "pages", "<OUT>"),
    files: files === null ? null : {
      count: count(files),
      fnv1a64: fnv1a64(new TextEncoder().encode(files)),
    },
    dirs: dirs === null ? null : {
      count: count(dirs),
      fnv1a64: fnv1a64(new TextEncoder().encode(dirs)),
    },
  };
}

// The base IR's own shape, so the test can say "the denominator is still the
// one these numbers were taken against" before comparing anything.
const index = JSON.parse(Deno.readTextFileSync(`${BASE_IR}/index.json`));

const fixture = {
  note:
    "Generated by tests/oracle/gen-impact-expected.ts from tools/impact-reference.sh --impl ts. " +
    "Paths are masked (<IR>/<OUT>) and *Seconds dropped; everything else is the prototype's bytes.",
  corpus: {
    modules: index.modules.length,
    declarations: index.declarationCount,
  },
  impact,
  prune,
};

Deno.writeTextFileSync(OUT, JSON.stringify(fixture, null, 2) + "\n");
console.log(`${OUT}: ${IMPACT.length} impact + ${PRUNE.length} prune scenarios`);
