#!/usr/bin/env -S deno run --allow-read --allow-write
//
// Turn a reference tree written by `tools/ledger-reference.sh --impl ts` into
// the committed fixture `tests/data/ledger-expected.json`.
//
// The fixture is what makes `cargo test` mean something on a machine that does
// not have the measurement target: the sizes and digests below are the frozen
// prototype's answers, so a port that drifts fails even where the corpus test
// skips. With the corpus present the same test regenerates every file and
// compares it against these numbers.
//
// **The two key strings are substituted here, once, and nowhere else.**
// `extractKey.extractor` and `renderKey.renderer` name an implementation, and
// the port's are deliberately different (plan §6). The substitution is anchored
// on the key name because `extractKey.irGenerator` carries the *same* string as
// the prototype's `extractor` and must not move: it names whatever wrote the IR
// on disk, which really is stage4b.
//
// usage:
//   gen-ledger-expected.ts [--ref DIR] [--out FILE]
//                          [--extractor STR] [--renderer STR]

const argv = Deno.args.slice();
const opt = (name: string, dflt: string) => {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : dflt;
};

const REF = opt("--ref", "/private/tmp/lean-doc-relay/m3/ref");
const OUT = opt(
  "--out",
  new URL("../data/ledger-expected.json", import.meta.url).pathname,
);
const EXTRACTOR = opt("--extractor", "lean-doc extractor v1");
const RENDERER = opt("--renderer", "lean-doc renderer v1");

/** FNV-1a 64, the same digest the M1/M2 fixtures use. */
function fnv1a64(bytes: Uint8Array): string {
  let hash = 0xcbf29ce484222325n;
  for (const byte of bytes) {
    hash = BigInt.asUintN(64, (hash ^ BigInt(byte)) * 0x100000001b3n);
  }
  return hash.toString(16).padStart(16, "0");
}

const enc = new TextEncoder();
const dec = new TextDecoder();

function substitute(bytes: Uint8Array): Uint8Array {
  let text = dec.decode(bytes);
  for (
    const [key, was, now] of [
      ["extractor", "lean-doc/experiments/stage4b", EXTRACTOR],
      ["renderer", "lean-doc/experiments/stage4c", RENDERER],
    ] as const
  ) {
    text = text.replace(`"${key}":"${was}"`, `"${key}":"${now}"`);
  }
  return enc.encode(text);
}

const files: Record<string, { bytes: number; fnv1a64: string }> = {};
for (const entry of [...Deno.readDirSync(REF)].sort((a, b) => a.name < b.name ? -1 : 1)) {
  if (!entry.isFile) continue;
  const name = entry.name;
  // Durations differ between runs and the two tools word their logs
  // differently; neither is an artifact anybody consumes.
  if (name.includes("timings") || name.endsWith("-stdout.txt")) continue;
  const raw = Deno.readFileSync(`${REF}/${name}`);
  const bytes = name.startsWith("ledger-") && name.endsWith(".json") ? substitute(raw) : raw;
  files[name] = { bytes: bytes.length, fnv1a64: fnv1a64(bytes) };
}

const ledger = JSON.parse(Deno.readTextFileSync(`${REF}/ledger-sha256.json`));
const mathlib = JSON.parse(Deno.readTextFileSync(`${REF}/ledger-mathlib-sha256.json`));
const count = (l: { modules: { files: { bytes: number }[] }[] }) => ({
  modules: l.modules.length,
  oleanFiles: l.modules.reduce((a, m) => a + m.files.length, 0),
  oleanBytes: l.modules.reduce(
    (a, m) => a + m.files.reduce((b, f) => b + Math.max(f.bytes, 0), 0),
    0,
  ),
});

Deno.writeTextFileSync(
  OUT,
  JSON.stringify(
    {
      note:
        "Generated by tests/oracle/gen-ledger-expected.ts from a tree written by " +
        "tools/ledger-reference.sh --impl ts. Sizes and digests are the frozen " +
        "prototype's, with extractKey.extractor and renderKey.renderer substituted.",
      reference: REF,
      extractor: EXTRACTOR,
      renderer: RENDERER,
      target: ledger.target,
      package: count(ledger),
      dependency: count(mathlib),
      files,
    },
    null,
    2,
  ) + "\n",
);

console.log(`${Object.keys(files).length} files -> ${OUT}`);
