//! Every answer in this file was produced by the TypeScript prototype, not by
//! the Rust code it checks.
//!
//! `tests/data/autolink-expected.json` is generated by
//! `tests/oracle/gen-autolink-expected.ts`, which slices `renderDocString` and
//! its helpers out of `experiments/stage7d/render.ts` (frozen) and runs them
//! against the **real** IR and the **real** dependency map. Regenerate with:
//!
//! ```text
//! deno run --allow-read --allow-write \
//!   crates/lean-doc-render/tests/oracle/gen-autolink-expected.ts
//! deno run --allow-read crates/lean-doc-render/tests/oracle/gen-autolink-expected.ts --check
//! ```
//!
//! # Why the prototype and not doc-gen4
//!
//! The earlier steps of M1-c compared against doc-gen4 itself, which was
//! possible because `nameToLink?` reads nothing but `SiteContext.result` and an
//! empty `AnalyzerResult` makes every lookup miss. That is exactly the
//! configuration this step is undoing, so the same oracle would answer
//! `NoLinks` to every question.
//!
//! It would also be the wrong function. doc-gen4's `nameToLink?` and the
//! prototype's `nameToLink` are not the same: doc-gen4 has an environment and
//! uses `isPrivateName`, `name2ModIdx`, an automatically-generated-eliminator
//! fallback and `sameEnd`; the prototype has no environment and uses a
//! `_private.` prefix test, `known` + `linkIndex`, `knownModules` and a
//! component-suffix scan. **The prototype is the one that scores 439/439**, so
//! it is the one this port has to agree with (plan §5).
//!
//! # The two halves
//!
//! - The committed fixture is self-contained. Each case carries the three
//!   sources of its own world reduced to the names it looks up, and the
//!   generator proves the reduction is faithful by re-rendering with it.
//! - [`the_whole_corpus_matches_the_prototype`] runs all 4,858 docstrings
//!   against the real IR and the real `.lidx`, which is the only place the
//!   *building* of the name index is exercised on real data. It is skipped
//!   unless `LEAN_DOC_AUTOLINK_FULL` points at the generator's `--full` output.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::path::PathBuf;

use lean_doc_ir::IrTree;
use lean_doc_render::{
    ExternalLinks, LinkIndex, NameIndex, PageLinks, module_decl_names, page_root,
};
use serde::Deserialize;

const FIXTURE: &str = include_str!("data/autolink-expected.json");

const DEFAULT_IR: &str = "/private/tmp/lean-doc-relay/w7h/base-ir";
const DEFAULT_LINK_INDEX: &str = "/private/tmp/lean-doc-relay/w7c/linkindex/link-index.lidx";

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    oracle: String,
    /// Docstrings in the corpus the sample was drawn from.
    ir_docstrings: usize,
    known_entries: usize,
    link_index_entries: usize,
    known_modules: usize,
    ir_module_names: usize,
    lidx_module_names: usize,
    total_anchors: usize,
    cases_with_anchors: usize,
    /// Docstrings where the prototype's CommonMark subset differs from
    /// doc-gen4, taken from the md crate's fixture. Excluded from the full
    /// comparison: there this crate is on doc-gen4's side by design.
    prototype_differs: Vec<String>,
    /// Cases where the prototype puts an anchor inside an anchor. See
    /// [`the_prototype_is_the_one_that_nests_anchors`].
    prototype_nests_anchors: Vec<String>,
    /// How many of those are real docstrings.
    real_docstrings_nesting_anchors: usize,
    cases: Vec<Case>,
}

/// One case, and the whole world it resolves against.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Case {
    what: String,
    root: String,
    /// What `nameToLink`'s last branch scans, in the order it scans it.
    decl_names: Vec<String>,
    /// The IR's name -> module map.
    known: BTreeMap<String, String>,
    /// The dependency closure's map, as `.lidx` text.
    lidx: String,
    /// Module names contributed by the IR itself.
    ir_modules: Vec<String>,
    md: String,
    html: String,
}

impl Case {
    /// The case's [`NameIndex`], built from its three sources the way a run
    /// builds it from the IR and the `.lidx`.
    fn index(&self) -> NameIndex {
        let mut builder = NameIndex::builder();
        for module in &self.ir_modules {
            builder.module_name(module);
        }
        for (name, module) in &self.known {
            builder.declaration(name, module);
        }
        // M7-c: the prototype had no dependency map, so its bytes are the
        // **fallback** branch — which an empty [`ExternalLinks`] reproduces
        // exactly. With a map every link into a dependency moves, on purpose
        // (`docs/implementation-plan.md` §1).
        builder.build(LinkIndex::parse(&self.lidx), ExternalLinks::default())
    }

    fn render(&self) -> String {
        let index = self.index();
        let names: Vec<&str> = self.decl_names.iter().map(String::as_str).collect();
        let links = PageLinks::new(&index, &self.root, &names);
        links.renderer().docstring(&self.md)
    }
}

fn expected() -> Expected {
    serde_json::from_str(FIXTURE).expect("tests/data/autolink-expected.json is valid")
}

#[test]
fn fixture_is_the_prototypes_own_output() {
    let e = expected();
    assert!(e.oracle.contains("render.ts"), "{}", e.oracle);
    assert!(e.oracle.contains("--link-index"), "{}", e.oracle);
    assert!(
        e.cases.len() >= 150,
        "only {} cases; the sample stopped covering the corpus",
        e.cases.len()
    );
    assert!(
        e.cases
            .iter()
            .filter(|c| c.what.starts_with("curated: "))
            .count()
            >= 25,
        "the hand-written cases are what reach the corners the package has none of"
    );
    // Carried from the md crate's fixture rather than restated, so that the two
    // lists of "where the prototype is not the authority" cannot drift apart.
    assert_eq!(
        e.prototype_differs,
        ["InformationTheory.Shannon.TimeBandLimiting.Count module doc 1"],
        "the CommonMark-subset divergence list changed; re-run the md crate's \
         generator and this one in the same session"
    );
}

/// What the corpus is, pinned so that a number quoted anywhere else can be
/// traced to a run of the generator rather than to a memory of one.
#[test]
fn the_corpus_numbers_are_what_was_measured() {
    let e = expected();
    assert_eq!(e.ir_docstrings, 4_858, "distinct docstrings in the IR");
    assert_eq!(e.known_entries, 5_296, "names in `known`");
    assert_eq!(e.link_index_entries, 258_760, "names in the .lidx");
    assert_eq!(e.ir_module_names, 432, "modules in the IR");
    assert_eq!(e.lidx_module_names, 6_115, "modules in the .lidx @ section");
    assert_eq!(e.known_modules, 6_158, "the union of the three sources");
    assert_eq!(e.total_anchors, 5_495, "anchors over the whole corpus");
    assert_eq!(
        e.cases_with_anchors, 1_904,
        "docstrings that resolve at all"
    );
}

/// The comparison this file exists for.
#[test]
fn matches_the_prototype_on_every_case() {
    let e = expected();
    let nests: BTreeSet<&str> = e
        .prototype_nests_anchors
        .iter()
        .map(String::as_str)
        .collect();
    let mut failures = Vec::new();
    for case in &e.cases {
        if nests.contains(case.what.as_str()) {
            continue;
        }
        let got = case.render();
        if got != case.html {
            failures.push(format!(
                "{}\n  want: {}\n  got:  {}",
                case.what,
                show(&case.html),
                show(&got)
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ from the prototype:\n{}",
        failures.len(),
        e.cases.len(),
        failures.join("\n")
    );
}

/// The one place the prototype and doc-gen4 disagree about *resolution* rather
/// than about CommonMark.
///
/// `renderText` carries an `inLink` flag and renders a code span inside an
/// `<a>` as plain text (`DocString.lean:264`); `renderInline` auto-links every
/// code span unconditionally (`render.ts:1622`). Under `NoLinks` the two are
/// indistinguishable, which is why the 4,987-case doc-gen4 comparison of M1-c's
/// earlier step could not see it. Plan §5 decides such cases in doc-gen4's
/// favour, and `tests/docgen4_linked.rs` carries the positive expectation —
/// doc-gen4's own bytes for the same input.
///
/// **No docstring of the target package reaches it** 【実測: 0 of 4,858】, so
/// gate A is untouched. What is asserted here is that the difference is *real*:
/// a port that had reproduced the prototype's nesting would fail.
#[test]
fn the_prototype_is_the_one_that_nests_anchors() {
    let e = expected();
    assert_eq!(
        e.real_docstrings_nesting_anchors, 0,
        "a real docstring now nests anchors; the divergence has reached gate A's bytes"
    );
    assert!(
        !e.prototype_nests_anchors.is_empty(),
        "no case reaches the inLink divergence any more"
    );
    let nests: BTreeSet<&str> = e
        .prototype_nests_anchors
        .iter()
        .map(String::as_str)
        .collect();
    let mut seen = 0;
    for case in e.cases.iter().filter(|c| nests.contains(c.what.as_str())) {
        seen += 1;
        let got = case.render();
        assert_ne!(
            got, case.html,
            "{}: matches the prototype's nesting",
            case.what
        );
        assert_eq!(depth_of_anchors(&got), 1, "{}: nests anchors", case.what);
        assert!(depth_of_anchors(&case.html) > 1, "{}", case.what);
    }
    assert_eq!(seen, nests.len(), "the sample dropped a recorded case");
}

/// The deepest `<a>` nesting in a fragment: 1 for well-formed output.
fn depth_of_anchors(html: &str) -> usize {
    let mut depth = 0usize;
    let mut max = 0usize;
    let mut rest = html;
    loop {
        let open = rest.find("<a ");
        let close = rest.find("</a>");
        match (open, close) {
            (Some(o), c) if c.is_none_or(|c| o < c) => {
                depth += 1;
                max = max.max(depth);
                rest = &rest[o + 3..];
            }
            (_, Some(c)) => {
                depth = depth.saturating_sub(1);
                rest = &rest[c + 4..];
            }
            _ => return max,
        }
    }
}

/// The sample has to keep reaching every branch of the resolver, or the test
/// above decays into one that a resolver returning `None` would pass.
///
/// Each entry names a shape only one branch produces.
#[test]
fn the_sample_reaches_every_branch() {
    let e = expected();
    let anchors: Vec<(String, String)> = e.cases.iter().flat_map(|c| anchors_of(&c.html)).collect();
    assert!(
        anchors.len() >= 200,
        "only {} anchors in the sample",
        anchors.len()
    );

    let any = |p: &dyn Fn(&str, &str) -> bool| anchors.iter().any(|(h, t)| p(h, t));
    // Branch 2: the name is documented, so the link carries its fragment.
    assert!(
        any(&|h, t| h.ends_with(&format!("#{t}"))),
        "no anchor whose fragment is the name itself"
    );
    // Branch 3: the name is a module, so there is no fragment at all.
    assert!(
        any(&|h, t| !h.contains('#') && h.ends_with(".html") && !t.ends_with(".lean")),
        "no anchor to a module page"
    );
    // Branch 4: the fragment is a *different* name — the one this page declares.
    assert!(
        any(&|h, t| h.contains('#') && !h.ends_with(&format!("#{t}"))),
        "no anchor produced by the component-suffix scan"
    );
    // `nameToLink`'s first branch, which the renderer answers itself.
    assert!(
        any(&|_, t| t.ends_with(".lean")),
        "no anchor for a source path"
    );
    // `extendLink`'s fallback for an unresolved `##name`.
    assert!(
        any(&|h, _| h.contains("find/?pattern=")),
        "no name search falling back to the find page"
    );
    // The characters an ASCII notion of a name would reject.
    assert!(
        any(&|_, t| t.contains('\'') || t.contains('!') || t.contains('?')),
        "no name containing an apostrophe, a bang or a question mark"
    );
    // The letter-like range above the BMP.
    assert!(
        any(&|_, t| t.chars().any(|c| c as u32 > 0xffff)),
        "no name containing a scalar above U+FFFF"
    );
    // Auto-linking inside a fenced code block, not just a code span.
    assert!(
        e.cases.iter().any(|c| c.html.contains("<pre><code")
            && c.html[c.html.find("<pre><code").unwrap_or(0)..].contains("<a href=")),
        "no anchor inside a code block"
    );
    // Every root the pages use has to appear, since it prefixes every link.
    let roots: BTreeSet<&str> = e.cases.iter().map(|c| c.root.as_str()).collect();
    assert!(
        roots.len() >= 3,
        "only {roots:?}; a resolver that ignored the root would pass"
    );
}

/// Every docstring of the target package, against the real IR and the real
/// dependency map.
///
/// Skipped unless `LEAN_DOC_AUTOLINK_FULL` names the generator's `--full`
/// output; that file is 5.6 MB and does not belong in the repository.
///
/// This is the only place [`NameIndex`] is built the way a run builds it —
/// dependency slices, then declarations, then references, then the `.lidx` —
/// so it is what stands behind the claim that the reduced worlds above are the
/// same thing in miniature.
#[test]
fn the_whole_corpus_matches_the_prototype() {
    let Ok(path) = std::env::var("LEAN_DOC_AUTOLINK_FULL") else {
        eprintln!(
            "skipping: set LEAN_DOC_AUTOLINK_FULL to the output of \
             tests/oracle/gen-autolink-expected.ts --full"
        );
        return;
    };
    let ir_dir = env_path("LEAN_DOC_IR", DEFAULT_IR);
    let lidx_path = env_path("LEAN_DOC_LINK_INDEX", DEFAULT_LINK_INDEX);

    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct Full {
        prototype_differs: Vec<String>,
        cases: Vec<FullCase>,
    }
    #[derive(Deserialize)]
    struct FullCase {
        what: String,
        module: String,
        root: String,
        md: String,
        html: String,
    }

    let text = std::fs::read_to_string(&path).expect("LEAN_DOC_AUTOLINK_FULL is readable");
    let full: Full = serde_json::from_str(&text).expect("the --full file is valid");

    let tree = IrTree::open(&ir_dir).expect("the IR opens");
    let modules = tree.load_modules().expect("every module reads");
    let mut builder = NameIndex::builder();
    for dep in tree.load_dep_maps().expect("every dependency slice reads") {
        builder.dep_map(&dep);
    }
    for module in &modules {
        builder.module(module);
    }
    // M7-c: the prototype had no dependency map, so its bytes are the
    // **fallback** branch — which an empty [`ExternalLinks`] reproduces
    // exactly. With a map every link into a dependency moves, on purpose
    // (`docs/implementation-plan.md` §1).
    let index = builder.build(
        LinkIndex::read(&lidx_path).expect("the .lidx reads"),
        ExternalLinks::default(),
    );
    eprintln!(
        "{} names / {} in the .lidx / {} modules",
        index.len(),
        index.link_index_len(),
        index.known_module_count()
    );

    let decl_names: HashMap<&str, Vec<&str>> = modules
        .iter()
        .map(|m| (m.module.as_str(), module_decl_names(m)))
        .collect();

    let excluded: BTreeSet<&str> = full.prototype_differs.iter().map(String::as_str).collect();
    let mut compared = 0usize;
    let mut matched = 0usize;
    let mut failures = Vec::new();
    for case in &full.cases {
        if excluded.contains(case.what.as_str()) {
            continue;
        }
        // `getRoot` is an input to both sides, so check it rather than trust it.
        assert_eq!(page_root(&case.module), case.root, "{}", case.what);
        let names = &decl_names[case.module.as_str()];
        let links = PageLinks::new(&index, &case.root, names);
        let got = links.renderer().docstring(&case.md);
        compared += 1;
        if got == case.html {
            matched += 1;
        } else if failures.len() < 20 {
            failures.push(format!(
                "{}\n  want: {}\n  got:  {}",
                case.what,
                show(&case.html),
                show(&got)
            ));
        }
    }
    eprintln!(
        "whole corpus: {matched} of {compared} match the prototype \
         ({} excluded as known CommonMark-subset differences)",
        full.cases.len() - compared
    );
    assert_eq!(
        matched,
        compared,
        "{} differ:\n{}",
        compared - matched,
        failures.join("\n")
    );
    assert!(compared >= 4_800, "only {compared} cases were compared");
}

// ------------------------------------------------------------------- helpers

fn env_path(var: &str, default: &str) -> PathBuf {
    PathBuf::from(std::env::var(var).unwrap_or_else(|_| default.to_owned()))
}

/// `(href, text)` of every anchor whose text is plain, which is every anchor
/// `autoLinkInline` makes.
fn anchors_of(html: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut rest = html;
    while let Some(at) = rest.find("<a href=\"") {
        rest = &rest[at + 9..];
        let Some(end) = rest.find('"') else { break };
        let href = unescape(&rest[..end]);
        rest = &rest[end + 2..];
        let Some(close) = rest.find("</a>") else {
            break;
        };
        let text = &rest[..close];
        if !text.contains('<') {
            out.push((href, unescape(text)));
        }
        rest = &rest[close + 4..];
    }
    out
}

fn unescape(s: &str) -> String {
    s.replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&amp;", "&")
}

/// Renders a string so a failure names the code points rather than printing
/// control characters into the terminal.
fn show(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c == '\n' {
            out.push_str("\\n");
        } else if (c.is_ascii_graphic() || c == ' ') || !c.is_control() {
            out.push(c);
        } else {
            out.push_str(&format!("<U+{:04X}>", c as u32));
        }
    }
    out
}
