//! The referee: **doc-gen4's own bytes** for docstrings whose names resolve.
//!
//! `tests/data/docgen4-linked-expected.json` is generated by
//! `tests/oracle/gen-docgen4-linked-expected.ts`, which runs
//! `DocGen4.Output.docStringToHtml` under `lake env lean` in the measurement
//! target with `AnalyzerResult.name2ModIdx` and `.moduleNames` filled in.
//! Regenerate with:
//!
//! ```text
//! deno run --allow-read --allow-write --allow-run --allow-env \
//!   crates/lean-doc-render/tests/oracle/gen-docgen4-linked-expected.ts
//! ```
//!
//! # Why a second oracle, when the target is the prototype
//!
//! Plan §5 is explicit that this port's target is `experiments/stage7d/render.ts`
//! and not doc-gen4: the two `nameToLink`s are different functions and it is the
//! prototype that scores 439/439. But M1-c's earlier doc-gen4 comparison ran
//! with an *empty* `AnalyzerResult`, so nothing had ever asked doc-gen4 what a
//! resolved docstring looks like — and "the prototype is the target" does not
//! mean "the prototype is right about everything".
//!
//! It was not. The first run of this file found that the prototype auto-links a
//! code span **inside an `<a>`** and doc-gen4 does not (`inLink`,
//! `DocString.lean:264` against `render.ts:1622`). Under `NoLinks` the two are
//! byte-identical, which is why 4,987 comparisons had not seen it. This crate
//! follows doc-gen4, and this file is where that expectation comes from.
//!
//! **No docstring of the target package reaches the difference** 【実測: 0 of
//! 4,858, `tests/autolink.rs`】, so gate A's bytes are unaffected.
//!
//! # The agreement zone
//!
//! The two specifications genuinely differ in three more places, and the corpus
//! avoids all three rather than papering over them — see the generator. The one
//! that is enforced *here* is the last: doc-gen4 runs with `currentName := none`,
//! so its module-local branch never fires, and these cases are therefore
//! rendered with an empty declaration list. `tests/autolink.rs` is what covers
//! that branch, against the prototype.

use std::collections::{BTreeMap, BTreeSet};

use lean_doc_render::{LinkIndex, NameIndex, PageLinks};
use serde::Deserialize;

const FIXTURE: &str = include_str!("data/docgen4-linked-expected.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    oracle: String,
    agreement_zone: String,
    lean_toolchain: String,
    /// Cases where the *prototype* does not produce doc-gen4's bytes.
    prototype_differs: Vec<String>,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    what: String,
    root: String,
    /// `AnalyzerResult.moduleNames`.
    modules: Vec<String>,
    /// `AnalyzerResult.name2ModIdx`, as name -> module.
    names: BTreeMap<String, String>,
    md: String,
    html: String,
}

impl Case {
    fn render(&self) -> String {
        let mut builder = NameIndex::builder();
        for module in &self.modules {
            builder.module_name(module);
        }
        for (name, module) in &self.names {
            builder.declaration(name, module);
        }
        let index = builder.build(LinkIndex::default());
        // Empty: doc-gen4's module-local branch is disabled for this corpus.
        let links = PageLinks::new(&index, &self.root, &[]);
        links.renderer().docstring(&self.md)
    }
}

fn expected() -> Expected {
    serde_json::from_str(FIXTURE).expect("tests/data/docgen4-linked-expected.json is valid")
}

#[test]
fn fixture_is_doc_gen4s_own_output() {
    let e = expected();
    assert!(e.oracle.contains("docStringToHtml"), "{}", e.oracle);
    assert!(e.oracle.contains("AnalyzerResult"), "{}", e.oracle);
    assert!(
        e.agreement_zone.contains("currentName"),
        "{}",
        e.agreement_zone
    );
    assert_eq!(e.lean_toolchain, "leanprover/lean4:v4.31.0");
    assert!(e.cases.len() >= 120, "only {} cases", e.cases.len());
    // A corpus in which nothing resolves would pass every assertion below.
    let anchors: usize = e
        .cases
        .iter()
        .map(|c| c.html.matches("<a href=").count())
        .sum();
    assert!(
        anchors >= 200,
        "only {anchors} anchors in doc-gen4's answers"
    );
}

/// The comparison this file exists for.
#[test]
fn matches_doc_gen4_on_every_case() {
    let e = expected();
    let mut failures = Vec::new();
    for case in &e.cases {
        let got = case.render();
        if got != case.html {
            failures.push(format!(
                "{}\n  want: {}\n  got:  {}",
                case.what, case.html, got
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ from doc-gen4:\n{}",
        failures.len(),
        e.cases.len(),
        failures.join("\n")
    );
}

/// The inputs on which the prototype is *not* the authority, named rather than
/// counted.
///
/// If this list ever grows past the `inLink` pair, the new entry is a place
/// where `tests/autolink.rs` is asserting the wrong expectation, and it has to
/// be looked at before either fixture is regenerated.
#[test]
fn the_prototype_differs_only_where_it_nests_anchors() {
    let e = expected();
    let differs: BTreeSet<&str> = e.prototype_differs.iter().map(String::as_str).collect();
    assert_eq!(
        differs,
        BTreeSet::from([
            "curated: a code span inside a link is not auto-linked",
            "curated: a code span inside an emphasised link is not auto-linked",
        ]),
        "the set of prototype-vs-doc-gen4 differences changed"
    );
    // And doc-gen4's answer really is the un-nested one, so that the assertion
    // in `tests/autolink.rs` stands on bytes rather than on a reading.
    for case in e.cases.iter().filter(|c| differs.contains(c.what.as_str())) {
        assert!(
            case.html.contains("<code>Pkg.A.f</code>"),
            "{}: {}",
            case.what,
            case.html
        );
    }
}

/// Every case a real docstring contributed agreed with doc-gen4 when the
/// fixture was generated. Recorded so that a corpus which quietly became
/// hand-written only would fail.
#[test]
fn most_of_the_corpus_is_real_docstrings() {
    let e = expected();
    let real = e
        .cases
        .iter()
        .filter(|c| !c.what.starts_with("curated: "))
        .count();
    assert!(real >= 100, "only {real} real docstrings in the corpus");
    assert!(
        e.prototype_differs
            .iter()
            .all(|w| w.starts_with("curated: ")),
        "a real docstring now separates the prototype from doc-gen4"
    );
}
