//! Every page in this file was written by the frozen TypeScript prototype, not
//! by the Rust code it checks.
//!
//! `tests/data/pages-expected.json` is generated by
//! `tests/oracle/gen-pages-expected.ts`, which runs
//! `experiments/stage7d/render.ts` **as a program** over small synthetic IR
//! trees and records the tree of pages it produced. Regenerate with:
//!
//! ```text
//! deno run --allow-read --allow-write --allow-run \
//!   crates/lean-doc-render/tests/oracle/gen-pages-expected.ts
//! deno run --allow-read --allow-write --allow-run \
//!   crates/lean-doc-render/tests/oracle/gen-pages-expected.ts --check
//! ```
//!
//! # Why a program and not a slice
//!
//! The other oracles in this crate slice a function out of the prototype and
//! call it. What M1-d3 ports is the prototype's *top level*: the order the name
//! maps are built in, the site-wide suppressed set, and which modules get a
//! page. Slicing that would mean re-implementing it in order to test it.
//!
//! # What this file does **not** stand on
//!
//! The real corpus. That is [`pages_match_the_reference_tree`] (env-gated) and
//! `tools/render-compare.sh`, which compares all 432 pages against the
//! prototype's own output. The cases here exist to reach the corners the corpus
//! has none of.
//!
//! # Eight of the twenty-one branches never fire on the real corpus
//!
//! 【実測, `branchTotals`】 — the corpus has no module without imports, no
//! module name needing HTML escaping, no `_private.` declaration, and no
//! module docstring sharing a position with a declaration. The last one is the
//! whole difference between the page order's real tie-breaker and the obvious
//! wrong one, and it is invisible to all 432 pages.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use lean_doc_render::{ExternalLinks, ModuleSet, RenderOptions, render_site};
use serde::Deserialize;

const FIXTURE: &str = include_str!("data/pages-expected.json");

const DEFAULT_IR: &str = "/private/tmp/lean-doc-relay/w7h/base-ir";
const DEFAULT_LINK_INDEX: &str = "/private/tmp/lean-doc-relay/w7c/linkindex/link-index.lidx";
const DEFAULT_REFERENCE: &str = "/private/tmp/lean-doc-relay/m1/ref-pages";

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    oracle: String,
    /// 40 hex digits, or `coverage.ts` scores the tree lower (plan 決定 1).
    source_url: String,
    ir_modules: usize,
    ir_declarations: usize,
    page_declarations: usize,
    suppressed_declarations: usize,
    /// How often each branch fires in one full run of the target package.
    branch_totals: BTreeMap<String, u64>,
    /// How many curated cases reach each branch.
    curated_branches: BTreeMap<String, u64>,
    /// The branches with a zero in `branch_totals`, as the generator listed
    /// them. Stored as well as derivable so a disagreement is itself a failure.
    never_fires: BTreeSet<String>,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Case {
    what: String,
    branches: Vec<String>,
    /// Set when the prototype's answer is the one that is wrong.
    note: Option<String>,
    /// The IR tree as bytes, keyed by path under its root.
    ir: BTreeMap<String, String>,
    lidx: String,
    link_index: bool,
    /// `null` = the run passed no `--only`; `[]` = a render set that came out
    /// empty, which the prototype cannot express.
    only: Option<Vec<String>>,
    /// The pages the prototype wrote, keyed by path under the site root.
    pages: BTreeMap<String, String>,
}

fn expected() -> Expected {
    serde_json::from_str(FIXTURE).expect("tests/data/pages-expected.json is valid")
}

#[test]
fn fixture_is_the_prototypes_own_output() {
    let e = expected();
    assert!(e.oracle.contains("render.ts"), "{}", e.oracle);
    assert!(e.oracle.contains("as a program"), "{}", e.oracle);
    assert!(e.cases.len() >= 12, "only {} cases", e.cases.len());
    let rev = e
        .source_url
        .rsplit_once("/blob/")
        .expect("the source URL is a /blob/<rev> prefix")
        .1;
    assert_eq!(rev.len(), 40, "{rev} is not a 40-hex revision");
    assert!(rev.bytes().all(|b| b.is_ascii_hexdigit()), "{rev}");
}

/// The comparison this file exists for.
///
/// One case is a recorded **disagreement**: `render.ts` cannot say "render no
/// modules", so its answer to an empty render set is every page. That case is
/// checked the other way round — see [`an_empty_render_set_renders_nothing`].
#[test]
fn every_case_reproduces_the_prototypes_pages() {
    let e = expected();
    let mut failures = Vec::new();
    let mut compared = 0usize;
    for case in &e.cases {
        if case.only.as_ref().is_some_and(Vec::is_empty) {
            continue;
        }
        let work = TempDir::new(&case.what);
        let got = case.render(&work);
        if got != case.pages {
            failures.push(describe(&case.what, &case.pages, &got));
        }
        compared += case.pages.len();
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ from the prototype:\n{}",
        failures.len(),
        e.cases.len(),
        failures.join("\n")
    );
    assert!(compared >= 14, "only {compared} pages were compared");
}

/// The hole plan §5 names: `render.ts:2088` reads the module filter off the
/// *presence* of a repeated flag, so a render set that came out empty means
/// "every module". The incremental pipeline had to guard the call in shell
/// (`incremental.sh:367`), and with revisions out of the bytes an empty set is
/// the common case.
///
/// The fixture records what the prototype does. This test asserts the port does
/// not, which is the one place in the suite where "differs from the oracle" is
/// the passing outcome.
#[test]
fn an_empty_render_set_renders_nothing() {
    let e = expected();
    let case = e
        .cases
        .iter()
        .find(|c| c.only.as_ref().is_some_and(Vec::is_empty))
        .expect("the fixture records the prototype's answer to an empty render set");
    assert!(
        case.pages.len() >= 2,
        "the prototype rendered {} pages; if it ever renders none this test proves nothing",
        case.pages.len()
    );
    assert!(
        case.note
            .as_deref()
            .is_some_and(|n| n.contains("every module"))
    );

    let work = TempDir::new(&case.what);
    let got = case.render(&work);
    assert!(
        got.is_empty(),
        "an empty ModuleSet wrote {} pages: {:?}",
        got.len(),
        got.keys().collect::<Vec<_>>()
    );
}

/// What the corpus is, pinned so a number quoted elsewhere traces to a run of
/// the generator rather than to a memory of one.
///
/// Every count is an event of **one full run** of the target package — no
/// `--only`, with a `.lidx` — so they can be compared with one another.
#[test]
fn the_corpus_numbers_are_what_was_measured() {
    let e = expected();
    assert_eq!(e.ir_modules, 432);
    assert_eq!(e.ir_declarations, 4_750);
    assert_eq!(e.page_declarations, 4_560);
    // 実測. `render.ts:2042` says 186 in a comment; that number is older than
    // this IR.
    assert_eq!(e.suppressed_declarations, 190);
    assert_eq!(
        e.branch_totals,
        BTreeMap::from(
            [
                // page items
                ("moduleDocItems", 1_515),
                ("pageDeclItems", 4_560),
                ("suppressedSkipped", 190),
                ("moduleWithoutModuleDocs", 8),
                ("moduleWithoutPageEntries", 26),
                ("moduleWithoutImports", 0),
                ("emptyPage", 1),
                // page order
                ("docAfterFirstDecl", 831),
                ("tieDocVsDecl", 0),
                ("tieDeclVsDecl", 2),
                // paths and names
                ("topLevelPagePath", 1),
                ("nestedPagePath", 431),
                ("moduleNameNeedsEscaping", 0),
                ("privateNameSkipped", 0),
                // the run's inputs
                ("depMapEntries", 3),
                ("linkIndexUsed", 1),
                ("linkIndexAbsent", 0),
                ("onlyAll", 432),
                ("onlyThese", 0),
                ("onlySkipped", 0),
                ("emptyOnly", 0),
            ]
            .map(|(k, n)| (k.to_owned(), n))
        ),
        "the branch profile of the corpus changed"
    );

    // Cross-checks between counters that have to agree by construction.
    assert_eq!(
        e.branch_totals["pageDeclItems"] + e.branch_totals["suppressedSkipped"],
        e.ir_declarations as u64
    );
    assert_eq!(
        e.branch_totals["topLevelPagePath"] + e.branch_totals["nestedPagePath"],
        e.ir_modules as u64,
        "every module's page goes somewhere"
    );
    assert_eq!(
        e.branch_totals["onlyAll"], e.ir_modules as u64,
        "the profile is a full run"
    );
    // The interleaving is real: 831 module docstrings sort after a declaration,
    // so "the docstrings first, then the declarations" would be a different
    // page and not a different ordering of the same one.
    assert!(e.branch_totals["docAfterFirstDecl"] > 0);
}

/// The eight branches no module of the target package reaches, and the fact
/// that the curated cases do reach them.
#[test]
fn the_curated_cases_cover_what_the_package_does_not() {
    let e = expected();
    let never: BTreeSet<String> = e
        .branch_totals
        .iter()
        .filter(|(_, n)| **n == 0)
        .map(|(k, _)| k.clone())
        .collect();
    assert_eq!(
        never, e.never_fires,
        "the generator and the totals disagree about which branches are dead"
    );
    assert_eq!(
        never,
        BTreeSet::from(
            [
                // A module docstring never shares a position with a
                // declaration in this package, so the page order's tie-breaker
                // — a running sequence number rather than `Decl::index` — is
                // invisible to all 432 pages.
                "tieDocVsDecl",
                "moduleNameNeedsEscaping",
                "moduleWithoutImports",
                "privateNameSkipped",
                // The three shapes of the module filter that a full run is not.
                "onlyThese",
                "onlySkipped",
                "emptyOnly",
                // The product always passes a `.lidx` (plan 決定 4).
                "linkIndexAbsent",
            ]
            .map(str::to_owned)
        ),
        "which branches the target package never reaches has changed"
    );
    for branch in &never {
        assert!(
            e.curated_branches.get(branch).copied().unwrap_or(0) > 0,
            "{branch} fires nowhere in the corpus and nowhere in the curated cases either"
        );
    }
    let all: BTreeSet<&String> = e.branch_totals.keys().collect();
    let curated: BTreeSet<&String> = e
        .curated_branches
        .iter()
        .filter(|(_, n)| **n > 0)
        .map(|(k, _)| k)
        .collect();
    assert_eq!(all, curated, "the curated cases stopped covering a branch");
}

/// The sample has to keep reaching every shape, read off the **fixture's own
/// bytes** — which came from the prototype — rather than off anything this
/// crate produced.
#[test]
fn the_sample_reaches_every_shape() {
    let e = expected();
    let pages = || e.cases.iter().flat_map(|c| c.pages.iter());
    let any = |what: &str, p: &dyn Fn(&String, &String) -> bool| {
        assert!(
            pages().any(|(path, html)| p(path, html)),
            "no page with {what}"
        );
    };

    any("a page at the site root", &|path, _| !path.contains('/'));
    any("a page four directories down", &|path, _| {
        path.matches('/').count() >= 4
    });
    any("a module docstring", &|_, html| {
        html.contains("<div class=\"mod_doc\">")
    });
    any("no page entries at all", &|_, html| {
        html.contains("<main>\n</main>")
    });
    any("a declaration docstring", &|_, html| {
        html.contains("<div class=\"decl\"") && html.contains("<p>See ")
    });
    any("a link into another module", &|_, html| {
        html.contains("<a href=\".././Pkg/One.html#Pkg.One.a\">")
    });
    any("a link to a module the .lidx alone knows", &|_, html| {
        html.contains("<a href=\".././Dep/Only/Module.html\">")
    });
    any(
        "a link through the .lidx's declaration section",
        &|_, html| html.contains("<a href=\".././Dep/M.html#Dep.M.thing\">"),
    );
    any("a link through a dependency slice", &|_, html| {
        html.contains("<a href=\".././Dep/Home.html#Dep.thing\">")
    });
    any("a module name that needs escaping", &|_, html| {
        html.contains("<title>Pkg.A&lt;B&amp;C&quot;D</title>")
    });
    any("an unresolved name left as a code span", &|_, html| {
        html.contains("<p>See <code>Dep.Only.Module</code> and <code>Dep.M.thing</code>.</p>")
    });

    // The one shape the corpus cannot show: the second module docstring sorts
    // before the declaration it shares a position with.
    let tie = e
        .cases
        .iter()
        .find(|c| c.branches.iter().any(|b| b == "tieDocVsDecl"))
        .expect("a case reaches the doc/declaration tie");
    let html = tie.pages.values().next().expect("it wrote a page");
    let second_doc = html.find("the second section").expect("the docstring");
    let tied_decl = html
        .find("<div class=\"decl\" id=\"Pkg.Two.b\">")
        .expect("the declaration at the same position");
    assert!(
        second_doc < tied_decl,
        "the prototype put the declaration first; the tie-breaker in the fixture is not the one \
         being tested"
    );
}

/// **M7-c**, over the same curated corpus: the three dependency-link shapes the
/// test above reads out of the prototype's bytes, rendered again with a
/// dependency map, become that package's version-pinned source.
///
/// The oracle here is **not** the prototype and cannot be — it has no notion of
/// a dependency's revision. What is asserted instead is a property of the pair
/// of runs, which is stronger than a recorded expectation would be:
///
/// 1. every byte outside an `href` attribute is identical to the empty-map run;
/// 2. the hrefs are the same in number and in order;
/// 3. every href that moved was a link into `Dep`, and moved to `Dep`'s blob URL;
/// 4. no href into the package being documented moved.
///
/// So the empty-map run keeps the prototype as its oracle
/// ([`every_case_reproduces_the_prototypes_pages`]) and this one says exactly
/// what the map added on top of it.
#[test]
fn a_dependency_map_moves_exactly_the_links_into_the_dependency() {
    let e = expected();
    let external = ExternalLinks::new([("Dep", DEP_BASE)]);
    let mut moved: BTreeSet<String> = BTreeSet::new();
    let mut cases_with_a_dependency_link = 0usize;

    for case in &e.cases {
        if case.only.as_ref().is_some_and(Vec::is_empty) {
            continue;
        }
        let work = TempDir::new(&case.what);
        let before = case.render(&work);
        let work = TempDir::new(&case.what);
        let after = case.render_with(&work, &external);
        assert_eq!(
            before.keys().collect::<Vec<_>>(),
            after.keys().collect::<Vec<_>>(),
            "{}: the map changed which pages exist",
            case.what
        );
        let mut touched = false;
        for (path, want) in &before {
            let got = &after[path];
            let (want_between, want_hrefs) = split_hrefs(want);
            let (got_between, got_hrefs) = split_hrefs(got);
            assert_eq!(
                want_between, got_between,
                "{} {path}: the map changed a byte outside an href",
                case.what
            );
            assert_eq!(
                want_hrefs.len(),
                got_hrefs.len(),
                "{} {path}: the map added or dropped a link",
                case.what
            );
            for (was, now) in want_hrefs.iter().zip(&got_hrefs) {
                if was == now {
                    assert!(
                        !was.contains("/Dep/"),
                        "{} {path}: a link into Dep stayed relative: {was}",
                        case.what
                    );
                    continue;
                }
                touched = true;
                assert!(
                    was.contains("/Dep/"),
                    "{} {path}: {was} is not a link into Dep and moved anyway (-> {now})",
                    case.what
                );
                assert!(
                    now.starts_with(DEP_BASE) && now.ends_with(".lean"),
                    "{} {path}: {was} -> {now}",
                    case.what
                );
                moved.insert((*now).to_owned());
            }
        }
        if touched {
            cases_with_a_dependency_link += 1;
        }
    }

    // The three shapes `the_sample_reaches_every_shape` pins on the prototype's
    // side, by name, so a corpus that stopped exercising one of them fails here
    // rather than passing vacuously. The `.lidx` these cases carry is `#lidx1`
    // and has no ranges, so every URL is the file's — which is the fallback
    // §M7「行範囲が取れない宣言でリンクを消さない」 asks for.
    assert_eq!(
        moved.iter().map(String::as_str).collect::<Vec<_>>(),
        [
            // a link through the .lidx's declaration section (`Dep.M.thing`)
            &format!("{DEP_BASE}/Dep/M.lean"),
            // a link through a dependency slice (`Dep.thing` in `Dep.Home`)
            &format!("{DEP_BASE}/Dep/Home.lean"),
            // a module the .lidx alone knows (`Dep.Only.Module`)
            &format!("{DEP_BASE}/Dep/Only/Module.lean"),
        ]
        .map(String::as_str)
        .into_iter()
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect::<Vec<_>>(),
    );
    assert!(
        cases_with_a_dependency_link >= 2,
        "only {cases_with_a_dependency_link} case(s) have a link into a dependency"
    );
}

/// All 432 pages, against the tree the prototype wrote.
///
/// Skipped unless the reference tree is present. This is the same comparison
/// `tools/render-compare.sh` makes; it is here so that `cargo test` on a
/// machine that has the corpus does not need the shell script.
#[test]
fn pages_match_the_reference_tree() {
    let reference = PathBuf::from(
        std::env::var("LEAN_DOC_REFERENCE_PAGES").unwrap_or_else(|_| DEFAULT_REFERENCE.into()),
    );
    let ir = PathBuf::from(std::env::var("LEAN_DOC_IR").unwrap_or_else(|_| DEFAULT_IR.into()));
    let lidx = PathBuf::from(
        std::env::var("LEAN_DOC_LINK_INDEX").unwrap_or_else(|_| DEFAULT_LINK_INDEX.into()),
    );
    // Presence is counted in **files**, not directories: `/private/tmp` is
    // swept, and an emptied `ref-pages` leaves its directory behind. `is_dir()`
    // said yes to that and the comparison then failed for an environmental
    // reason — the same trap `lean-doc-incr/tests/impact.rs` documents.
    if file_count(&reference) == 0 || file_count(&ir) == 0 || !lidx.is_file() {
        eprintln!(
            "skipping: no corpus (empty or missing: {} / {} / {})",
            reference.display(),
            ir.display(),
            lidx.display(),
        );
        return;
    }
    let e = expected();
    let work = TempDir::new("reference");
    let summary = render_site(&RenderOptions {
        ir: &ir,
        pages: &work.path,
        source_url: &e.source_url,
        // M7-c: the reference tree is the **prototype's**, whose links into a
        // dependency are all relative. The empty map is what reproduces them;
        // this test is therefore an oracle for the fallback branch only, and
        // `benchmarks/results/m7c-*` is where the populated one is measured.
        external_links: &ExternalLinks::default(),
        link_index: Some(&lidx),
        only: &ModuleSet::All,
    })
    .expect("the corpus renders");
    assert_eq!(summary.pages_written, 432);
    assert_eq!(summary.declarations_rendered, 4_560);
    assert_eq!(summary.declarations_suppressed, 190);

    let want = read_tree(&reference);
    let got = read_tree(&work.path);
    assert_eq!(
        want.keys().collect::<Vec<_>>(),
        got.keys().collect::<Vec<_>>(),
        "the two trees have different files"
    );
    // The one page the prototype and md4c disagree on: a broken nested code
    // span in a module docstring, where doc-gen4 sides with this crate. Pinned
    // by name and by count, so a *second* divergence fails here.
    // 【実測, plan §5 / `lean-doc-md/tests/ts_docstring.rs`】
    let differing: Vec<&String> = want
        .iter()
        .filter(|(path, html)| got.get(*path) != Some(*html))
        .map(|(path, _)| path)
        .collect();
    assert_eq!(
        differing,
        ["InformationTheory/Shannon/TimeBandLimiting/Count.html"],
        "the set of pages that differ from the prototype changed"
    );
}

// ------------------------------------------------------------------- helpers

impl Case {
    /// Writes the case's IR into `work`, renders it, and reads the pages back.
    ///
    /// **The empty dependency map is what makes the prototype's bytes the right
    /// expectation** (M7-c): with one, every link into `Dep` becomes that
    /// package's pinned source and the prototype — which had no such notion —
    /// stops being an oracle for those hrefs.
    /// [`a_dependency_map_moves_exactly_the_links_into_the_dependency`] is the
    /// other side.
    fn render(&self, work: &TempDir) -> BTreeMap<String, String> {
        self.render_with(work, &ExternalLinks::default())
    }

    fn render_with(&self, work: &TempDir, external: &ExternalLinks) -> BTreeMap<String, String> {
        let ir = work.path.join("ir");
        for (name, text) in &self.ir {
            let path = ir.join(name);
            fs::create_dir_all(path.parent().expect("every IR file is under the root"))
                .expect("the temporary tree is writable");
            fs::write(&path, text).expect("the temporary tree is writable");
        }
        let lidx = work.path.join("link-index.lidx");
        fs::write(&lidx, &self.lidx).expect("the temporary tree is writable");
        let pages = work.path.join("pages");

        let only = match &self.only {
            None => ModuleSet::All,
            Some(names) => ModuleSet::These(names.iter().cloned().collect()),
        };
        let e = expected();
        render_site(&RenderOptions {
            ir: &ir,
            pages: &pages,
            source_url: &e.source_url,
            external_links: external,
            link_index: self.link_index.then_some(lidx.as_path()),
            only: &only,
        })
        .unwrap_or_else(|e| panic!("{}: {e}", self.what));
        read_tree(&pages)
    }
}

/// The prefix the `Dep` package's sources live under in the test below. 40 hex
/// digits, because plan 決定 1 wants one everywhere a revision reaches a URL.
const DEP_BASE: &str = "https://github.com/o/dep/blob/0123456789abcdef0123456789abcdef01234567";

/// Every `href="…"` in `html`, and the bytes between them.
///
/// Two documents whose `between` halves agree differ **only** inside href
/// attributes, which is the claim M7-c has to be held to.
fn split_hrefs(html: &str) -> (Vec<&str>, Vec<&str>) {
    let (mut between, mut hrefs) = (Vec::new(), Vec::new());
    let mut rest = html;
    while let Some(at) = rest.find("href=\"") {
        between.push(&rest[..at]);
        let value = &rest[at + 6..];
        let end = value.find('"').expect("an href attribute is closed");
        hrefs.push(&value[..end]);
        rest = &value[end..];
    }
    between.push(rest);
    (between, hrefs)
}

/// Regular files under `dir`, recursively. Zero for a missing directory.
fn file_count(dir: &Path) -> usize {
    let Ok(entries) = fs::read_dir(dir) else {
        return 0;
    };
    entries
        .flatten()
        .map(|entry| match entry.file_type() {
            Ok(kind) if kind.is_dir() => file_count(&entry.path()),
            Ok(kind) if kind.is_file() => 1,
            _ => 0,
        })
        .sum()
}

/// Every `.html` under `dir`, keyed by its path relative to it. A missing
/// directory is an empty tree: a run that renders nothing creates nothing.
fn read_tree(dir: &Path) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    fn walk(at: &Path, prefix: &str, out: &mut BTreeMap<String, String>) {
        let Ok(entries) = fs::read_dir(at) else {
            return;
        };
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().into_owned();
            if entry.path().is_dir() {
                walk(&entry.path(), &format!("{prefix}{name}/"), out);
            } else if name.ends_with(".html") {
                let text = fs::read_to_string(entry.path()).expect("a page reads back");
                out.insert(format!("{prefix}{name}"), text);
            }
        }
    }
    walk(dir, "", &mut out);
    out
}

fn describe(what: &str, want: &BTreeMap<String, String>, got: &BTreeMap<String, String>) -> String {
    let mut lines = vec![what.to_owned()];
    for path in want.keys().chain(got.keys()).collect::<BTreeSet<_>>() {
        match (want.get(path), got.get(path)) {
            (Some(a), Some(b)) if a == b => {}
            (Some(a), Some(b)) => {
                let at = a
                    .bytes()
                    .zip(b.bytes())
                    .position(|(x, y)| x != y)
                    .unwrap_or_else(|| a.len().min(b.len()));
                let from = at.saturating_sub(60);
                lines.push(format!(
                    "  {path} differs at byte {at}\n    want: …{}\n    got:  …{}",
                    &a[floor_char(a, from)..floor_char(a, (at + 90).min(a.len()))],
                    &b[floor_char(b, from)..floor_char(b, (at + 90).min(b.len()))],
                ));
            }
            (Some(_), None) => lines.push(format!("  {path} was not written")),
            (None, Some(_)) => lines.push(format!("  {path} should not exist")),
            (None, None) => unreachable!(),
        }
    }
    lines.join("\n")
}

/// The nearest char boundary at or below `at`, so slicing a page for a failure
/// message cannot itself panic.
fn floor_char(s: &str, mut at: usize) -> usize {
    while at > 0 && !s.is_char_boundary(at) {
        at -= 1;
    }
    at
}

/// A directory that removes itself, so a failed run does not leave a tree of
/// pages behind. Hand-rolled rather than a dependency: it is ten lines and the
/// workspace has no other use for one.
struct TempDir {
    path: PathBuf,
}

impl TempDir {
    fn new(what: &str) -> Self {
        use std::sync::atomic::{AtomicU32, Ordering};
        static NEXT: AtomicU32 = AtomicU32::new(0);
        let slug: String = what
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
            .take(40)
            .collect();
        let path = std::env::temp_dir().join(format!(
            "lean-doc-pages-{}-{}-{slug}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).expect("the temporary directory is creatable");
        Self { path }
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.path);
    }
}
