//! Every answer in this file was produced by the TypeScript prototype, not by
//! the Rust code it checks.
//!
//! `tests/data/page-parts-expected.json` is generated by
//! `tests/oracle/gen-page-parts-expected.ts`, which slices `declHeader`,
//! `declHtml`, `headHtml`, `pageHeaderHtml` and `internalNavHtml` out of
//! `experiments/stage7d/render.ts` (frozen) and runs them over the **real** IR
//! with the **real** `.lidx`. Regenerate with:
//!
//! ```text
//! deno run --allow-read --allow-write \
//!   crates/lean-doc-render/tests/oracle/gen-page-parts-expected.ts
//! deno run --allow-read \
//!   crates/lean-doc-render/tests/oracle/gen-page-parts-expected.ts --check
//! ```
//!
//! # Why the prototype and not doc-gen4
//!
//! Same reason as M1-d1: `docInfoToHtml` walks `DocInfo`s built from a live
//! environment, and the IR carries a flattened, already-printed form of them.
//! There is no input both implementations could be handed. The prototype is the
//! other consumer of that IR and it is the one scoring 439/439 (plan §1).
//!
//! # The two halves
//!
//! - The committed fixture is self-contained. Each case carries the three
//!   sources of its world reduced to the names it looks up, plus the module
//!   file reduced to what `containedNames` and `moduleDeclNames` read, and the
//!   generator proves each reduction faithful by re-rendering with it.
//! - [`the_whole_corpus_matches_the_prototype`] runs **all 4,750 headers, all
//!   4,560 declaration blocks and all 432 frames** against the real IR. It is
//!   skipped unless `LEAN_DOC_PAGE_PARTS_FULL` points at the generator's
//!   `--full` output (77 MB, which does not belong in the repository).
//!
//! # What the real corpus does not reach
//!
//! **Nine of the 41 branches never fire** over the whole package
//! (`branchTotals` in the fixture): there is no `class`, no `inductive` and no
//! `class_inductive` declaration, no structure whose constructor is not `mk`,
//! no structure without a `ctor` member, no inherited field whose projection is
//! declared inside the structure's range, no implicit binder on a field, and no
//! module without imports. A mutation to any of them is invisible to real data,
//! and [`the_curated_cases_cover_what_the_package_does_not`] refuses to let
//! that quietly stop being true.

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::path::PathBuf;

use lean_doc_ir::{Decl, IrTree, ModuleFile};
use lean_doc_render::{
    CodeRenderer, DeclRenderer, LinkIndex, NameIndex, PageLinks, UnplaceableName, decl_header,
    head_html, internal_nav_html, module_decl_names, module_source_url, page_header_html,
    page_root,
};
use serde::Deserialize;

const FIXTURE: &str = include_str!("data/page-parts-expected.json");

const DEFAULT_IR: &str = "/private/tmp/lean-doc-relay/w7h/base-ir";
const DEFAULT_LINK_INDEX: &str = "/private/tmp/lean-doc-relay/w7c/linkindex/link-index.lidx";

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    oracle: String,
    /// The revision prefix the source links were built with. 40 hex digits, or
    /// `coverage.ts` scores the tree lower (plan 決定 1).
    source_url: String,
    ir_modules: usize,
    /// Declarations in the IR — the `declHeader` denominator.
    ir_declarations: usize,
    /// Declarations that get a page entry — the `declHtml` denominator.
    page_declarations: usize,
    /// Names that appear as some declaration's member, across **every** module.
    suppressed_declarations: usize,
    known_entries: usize,
    link_index_entries: usize,
    known_modules: usize,
    /// How often each branch fires over the whole corpus.
    branch_totals: BTreeMap<String, u64>,
    /// How often each fires over the hand-written cases.
    curated_branches: BTreeMap<String, u64>,
    /// The branches with a zero in `branch_totals`, as the generator listed
    /// them. Stored as well as derivable so that a disagreement between the two
    /// is itself a failure.
    never_fires: BTreeSet<String>,
    cases: Vec<Case>,
    frames: Vec<Frame>,
}

/// One declaration, and the whole world it renders against.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Case {
    what: String,
    root: String,
    source_url: String,
    /// The module file, reduced: the rendered declaration verbatim, plus
    /// name/range/index stubs for the siblings when they turn out to matter.
    module: ModuleFile,
    /// Which declaration of `module` is rendered.
    at: usize,
    /// The IR's name -> module map.
    known: BTreeMap<String, String>,
    /// The dependency closure's map, as `.lidx` text.
    lidx: String,
    /// Module names contributed by the IR itself.
    ir_modules: Vec<String>,
    header: String,
    html: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Frame {
    what: String,
    module: String,
    root: String,
    source_url: String,
    imports: Vec<String>,
    member_names: Vec<String>,
    head: String,
    header: String,
    nav: String,
}

/// What one case produced here.
struct Got {
    header: String,
    html: Result<String, UnplaceableName>,
}

impl Case {
    /// The case's [`NameIndex`], built from its three sources the way a run
    /// builds it from the IR and the `.lidx`.
    fn index(&self) -> NameIndex {
        let mut builder = NameIndex::builder();
        for module in &self.ir_modules {
            builder.module_name(module);
        }
        for (name, module) in &self.known {
            builder.declaration(name, module);
        }
        builder.build(LinkIndex::parse(&self.lidx))
    }

    fn render(&self) -> Got {
        let index = self.index();
        let decl = &self.module.declarations[self.at];
        let code = CodeRenderer::new(&index);
        let header = decl_header(decl, &self.module.module, &code);
        let names = module_decl_names(&self.module);
        let links = PageLinks::new(&index, &self.root, &names);
        let docs = links.renderer();
        let renderer = DeclRenderer::new(&self.module, &self.root, &self.source_url, code, &docs);
        let html = renderer.decl_html(decl, &header);
        Got { header, html }
    }
}

impl Frame {
    fn names(&self) -> Vec<&str> {
        self.member_names.iter().map(String::as_str).collect()
    }
}

fn expected() -> Expected {
    serde_json::from_str(FIXTURE).expect("tests/data/page-parts-expected.json is valid")
}

#[test]
fn fixture_is_the_prototypes_own_output() {
    let e = expected();
    assert!(e.oracle.contains("render.ts"), "{}", e.oracle);
    assert!(e.oracle.contains("declHtml"), "{}", e.oracle);
    assert!(
        e.cases.len() >= 150,
        "only {} cases; the sample stopped covering the corpus",
        e.cases.len()
    );
    assert!(
        e.cases
            .iter()
            .filter(|c| c.what.starts_with("curated: "))
            .count()
            >= 18,
        "the hand-written cases are what reach the corners the package has none of"
    );
    assert!(
        e.frames
            .iter()
            .filter(|f| f.what.starts_with("curated: "))
            .count()
            >= 4
    );
    // Plan 決定 1: a tag or a branch here silently lowers the acceptance score,
    // because `coverage.ts` normalises `/blob/[0-9a-f]{40}/` and nothing else.
    let rev = e
        .source_url
        .rsplit_once("/blob/")
        .expect("the source URL is a /blob/<rev> prefix")
        .1;
    assert_eq!(rev.len(), 40, "{rev} is not a 40-hex revision");
    assert!(rev.bytes().all(|b| b.is_ascii_hexdigit()), "{rev}");
}

/// What the corpus is, pinned so that a number quoted anywhere else can be
/// traced to a run of the generator rather than to a memory of one.
///
/// **Two denominators, not one.** `declHeader` is computed for every
/// declaration in the IR; `declHtml` only for those that get a page entry,
/// which is the IR minus `suppressed` — the names that appear as some other
/// declaration's member, collected **across every module** (`render.ts`
/// 2043-2048). Collecting it per module leaves other modules' projections and
/// constructors on the page (plan §5).
#[test]
fn the_corpus_numbers_are_what_was_measured() {
    let e = expected();
    assert_eq!(e.ir_modules, 432);
    assert_eq!(e.ir_declarations, 4_750, "the declHeader denominator");
    assert_eq!(e.page_declarations, 4_560, "the declHtml denominator");
    assert_eq!(
        e.suppressed_declarations,
        e.ir_declarations - e.page_declarations,
        "every suppressed name is a declaration of some module, so the set's size \
         is exactly the number of pages entries lost"
    );
    // 実測. `render.ts:2042` says 186 in a comment; that number is older than
    // this IR, and the set is what was counted here.
    assert_eq!(e.suppressed_declarations, 190);
    assert_eq!(e.known_entries, 5_296, "names in `known`");
    assert_eq!(e.link_index_entries, 258_760, "names in the .lidx");
    assert_eq!(e.known_modules, 6_158);

    assert_eq!(
        e.branch_totals,
        BTreeMap::from(
            [
                // declHeader
                ("anchorsBreakWithin", 4_750),
                ("implArgs", 31_185),
                ("headerExplicitArg", 18_119),
                ("headerNoBinders", 106),
                ("extendsRendered", 1),
                ("headerStructureWithoutParents", 36),
                // declHtml
                ("ghLinks", 4_560),
                ("docstringsRendered", 3_277),
                ("declWithoutDocstring", 1_283),
                ("attributeBlocks", 104),
                ("attributeItems", 126),
                ("declWithoutAttributes", 4_456),
                ("kindStructure", 37),
                ("kindClass", 0),
                ("kindDefinition", 801),
                ("kindInstance", 91),
                ("kindInductive", 0),
                ("kindClassInductive", 0),
                ("kindOther", 3_631),
                // equationsHtml
                ("equationBlocks", 804),
                ("equationItems", 552),
                ("equationsOmittedNotices", 270),
                ("equationsDroppedOverLimit", 270),
                ("equationsAbsent", 88),
                // structureHtml / fieldToHtml
                ("memberTables", 37),
                ("memberFields", 156),
                ("memberFieldArgs", 49),
                ("memberFieldDocs", 117),
                ("memberFieldsInherited", 4),
                ("memberFieldsInheritedWithId", 0),
                ("fieldDirect", 152),
                ("fieldImplicitArg", 0),
                ("structureFieldsMk", 37),
                ("structureExt", 0),
                ("structureCtorMissing", 0),
                // the two stubs
                ("instancesForStubs", 838),
                ("classInstancesStubs", 0),
                // internalNavHtml
                ("navLinks", 4_560),
                ("importListItems", 3_503),
                ("importDuplicatesDropped", 432),
                ("navWithoutImports", 0),
                ("navWithoutMembers", 26),
            ]
            .map(|(k, n)| (k.to_owned(), n))
        ),
        "the branch profile of the corpus changed"
    );

    // Cross-checks between counters that have to agree by construction.
    assert_eq!(
        e.branch_totals["ghLinks"], e.page_declarations as u64,
        "every rendered declaration gets exactly one source link"
    );
    assert_eq!(
        e.branch_totals["navLinks"], e.page_declarations as u64,
        "and exactly one nav entry"
    );
    assert_eq!(
        e.branch_totals["anchorsBreakWithin"], e.ir_declarations as u64,
        "every header, page entry or not, links to itself"
    );
    assert_eq!(
        e.branch_totals["docstringsRendered"] + e.branch_totals["declWithoutDocstring"],
        e.page_declarations as u64
    );
    assert_eq!(
        e.branch_totals["fieldDirect"] + e.branch_totals["memberFieldsInherited"],
        e.branch_totals["memberFields"]
    );
    assert_eq!(
        e.branch_totals["kindStructure"] + e.branch_totals["kindClass"],
        e.branch_totals["memberTables"],
        "a members table comes from a structure or a class and from nothing else"
    );
    assert_eq!(
        e.branch_totals["instancesForStubs"],
        e.branch_totals["kindStructure"]
            + e.branch_totals["kindDefinition"]
            + e.branch_totals["kindInductive"]
    );
}

/// The comparison this file exists for, over the committed sample.
#[test]
fn matches_the_prototype_on_every_case() {
    let e = expected();
    let mut failures = Vec::new();
    for case in &e.cases {
        let got = case.render();
        if got.header != case.header {
            failures.push(format!(
                "{} (header)\n  want: {}\n  got:  {}",
                case.what,
                show(&case.header),
                show(&got.header)
            ));
            continue;
        }
        match got.html {
            Ok(html) if html == case.html => {}
            Ok(html) => failures.push(format!(
                "{}\n  want: {}\n  got:  {}",
                case.what,
                show(&case.html),
                show(&html)
            )),
            Err(e) => failures.push(format!("{}: {e}", case.what)),
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ from the prototype:\n{}",
        failures.len(),
        e.cases.len(),
        failures.join("\n")
    );
}

#[test]
fn frames_match_the_prototype() {
    let e = expected();
    let mut failures = Vec::new();
    for frame in &e.frames {
        let mut check = |what: &str, got: String, want: &str| {
            if got != *want {
                failures.push(format!(
                    "{} ({what})\n  want: {}\n  got:  {}",
                    frame.what,
                    show(want),
                    show(&got)
                ));
            }
        };
        check("head", head_html(&frame.module, &frame.root), &frame.head);
        check(
            "header",
            page_header_html(&frame.module, &frame.root),
            &frame.header,
        );
        check(
            "nav",
            internal_nav_html(
                &frame.module,
                &frame.root,
                &frame.source_url,
                &frame.imports,
                &frame.names(),
            ),
            &frame.nav,
        );
        check("root", page_root(&frame.module), &frame.root);
        check(
            "sourceUrl",
            module_source_url(&e.source_url, &frame.module),
            &frame.source_url,
        );
    }
    assert!(
        failures.is_empty(),
        "{} of {} frames differ from the prototype:\n{}",
        failures.len(),
        e.frames.len(),
        failures.join("\n")
    );
}

/// The nine branches no real declaration or module reaches, and the fact that
/// the curated cases do reach them.
#[test]
fn the_curated_cases_cover_what_the_package_does_not() {
    let e = expected();
    let never: BTreeSet<String> = e
        .branch_totals
        .iter()
        .filter(|(_, n)| **n == 0)
        .map(|(k, _)| k.clone())
        .collect();
    assert_eq!(
        never, e.never_fires,
        "the generator and the totals disagree about which branches are dead"
    );
    assert_eq!(
        never,
        BTreeSet::from(
            [
                "classInstancesStubs",
                "fieldImplicitArg",
                "kindClass",
                "kindClassInductive",
                "kindInductive",
                "memberFieldsInheritedWithId",
                "navWithoutImports",
                "structureCtorMissing",
                "structureExt",
            ]
            .map(str::to_owned)
        ),
        "which branches the target package never reaches has changed"
    );
    for branch in &never {
        assert!(
            e.curated_branches.get(branch).copied().unwrap_or(0) > 0,
            "{branch} fires nowhere in the corpus and nowhere in the curated cases either: \
             nothing would catch a mutation to it"
        );
    }
    // And the curated set reaches everything, not only the nine.
    let all: BTreeSet<&String> = e.branch_totals.keys().collect();
    let curated: BTreeSet<&String> = e
        .curated_branches
        .iter()
        .filter(|(_, n)| **n > 0)
        .map(|(k, _)| k)
        .collect();
    assert_eq!(all, curated, "the curated cases stopped covering a branch");
}

/// The sample has to keep reaching every shape, or the comparison above decays
/// into one that a renderer emitting only headers would pass.
///
/// Every assertion here reads the **fixture's own bytes**, which came from the
/// prototype, rather than anything this crate produced.
#[test]
fn the_sample_reaches_every_shape() {
    let e = expected();
    let any = |what: &str, p: &dyn Fn(&Case) -> bool| {
        assert!(e.cases.iter().any(p), "no case with {what}");
    };

    // The one element at this level that is not flattened, and therefore the
    // one whose trailing newline is part of it.
    any("an attribute block ending in a newline", &|c| {
        c.html.contains("</div>\n<div class=\"decl_header\">")
    });
    any("more than one attribute", &|c| {
        c.html.contains("<div class=\"attributes\">@[")
            && c.html
                .split("<div class=\"attributes\">@[")
                .nth(1)
                .is_some_and(|s| s[..s.find(']').unwrap_or(0)].contains(", "))
    });
    any("an equations block", &|c| {
        c.html.contains("<ul class=\"equations\">")
    });
    any("the over-the-limit notice", &|c| {
        c.html
            .contains("One or more equations did not get rendered")
    });
    any("an instances-for stub", &|c| {
        c.html.contains("class=\"instances-for-list\"")
    });
    any("a class instances stub", &|c| {
        c.html.contains("<ul id=\"instances-list-")
    });
    any("an extends clause", &|c| {
        c.html
            .contains("<span class=\"decl_extends\">extends</span> ")
    });
    any("two parents joined by a comma", &|c| {
        c.html.contains("</span>, <span id=\"")
    });
    any("a members table in `mk` form", &|c| {
        c.html.contains("<ul class=\"structure_fields\" id=\"")
    });
    any("a members table in `structure_ext` form", &|c| {
        c.html.contains("<ul class=\"structure_ext\">")
    });
    any("a direct field", &|c| {
        c.html.contains("\" class=\"structure_field\">")
    });
    any("a field docstring", &|c| {
        c.html.contains("<div class=\"structure_field_doc\">")
    });
    any("an inherited field without an id", &|c| {
        c.html
            .contains("<li class=\"structure_field inherited_field\">")
    });
    any("an inherited field with an id", &|c| {
        c.html
            .contains("\" class=\"structure_field inherited_field\">")
    });
    any("an implicit binder", &|c| {
        c.html.contains("<span class=\"impl_arg\">")
    });
    any("a docstring", &|c| c.html.contains("<p>"));
    any("a name that needs escaping", &|c| {
        c.html.contains("<div class=\"decl\" id=\"")
            && c.html[c.html.find("id=\"").unwrap_or(0)..].starts_with("id=\"A&lt;B&amp;C")
    });
    // An unlinkable constant in a signature, which is a `span.fn` and not an
    // anchor. Every block has at least the header's own `break_within` link, so
    // "no anchor at all" is not a shape a declaration can have.
    any("an unlinkable constant", &|c| {
        c.html.contains("<span class=\"fn\">")
    });

    // Every CSS class `cssKind` can produce, since it is a second mapping next
    // to `kindDescription` and collapsing the two is the obvious mistake.
    let classes: BTreeSet<&str> = e
        .cases
        .iter()
        .filter_map(|c| {
            let at = c.html.find("\"><div class=\"")? + 14;
            let end = c.html[at..].find('"')? + at;
            Some(&c.html[at..end])
        })
        .collect();
    // `ctor` is absent on purpose: a constructor is always some structure's
    // `ctor` member, so it is in `suppressed` and never gets a page entry.
    for want in [
        "def",
        "class",
        "theorem",
        "structure",
        "instance",
        "inductive",
        "opaque",
    ] {
        assert!(classes.contains(want), "no `div.{want}`; got {classes:?}");
    }
    assert!(
        !classes.contains("definition") && !classes.contains("class_inductive"),
        "`cssKind` collapsed into the identity: {classes:?}"
    );

    // Every root the pages use, since it prefixes every link in a header.
    let roots: BTreeSet<&str> = e.cases.iter().map(|c| c.root.as_str()).collect();
    assert!(roots.len() >= 5, "only {roots:?}");
    let frame_roots: BTreeSet<&str> = e.frames.iter().map(|f| f.root.as_str()).collect();
    assert!(frame_roots.len() >= 5, "only {frame_roots:?}");

    // The frames' own corners.
    assert!(
        e.frames
            .iter()
            .any(|f| f.imports.len() != f.imports.iter().collect::<BTreeSet<_>>().len()),
        "no frame with a duplicate import; the de-duplication would be untested"
    );
    assert!(
        e.frames.iter().any(|f| f.imports.is_empty()),
        "no frame without imports"
    );
    assert!(
        e.frames.iter().any(|f| f.member_names.is_empty()),
        "no frame without page entries"
    );
    assert!(
        e.frames.iter().any(|f| f.module.contains('<')),
        "no module name that needs escaping"
    );
    assert!(
        e.frames
            .iter()
            .any(|f| f.member_names.iter().any(|n| n.contains('"'))),
        "no member name that needs escaping"
    );
}

/// Every header, every declaration block and every frame of the target package,
/// against the real IR and the real `.lidx`.
///
/// Skipped unless `LEAN_DOC_PAGE_PARTS_FULL` names the generator's `--full`
/// output; that file is 77 MB and does not belong in the repository.
///
/// This is the only place the whole-run inputs are built the way a run builds
/// them — the name index from the dependency slices, the modules and the
/// `.lidx`; `suppressed` from **every** module — so it is what stands behind
/// the claim that the reduced worlds above are the same thing in miniature.
#[test]
fn the_whole_corpus_matches_the_prototype() {
    let Ok(path) = std::env::var("LEAN_DOC_PAGE_PARTS_FULL") else {
        eprintln!(
            "skipping: set LEAN_DOC_PAGE_PARTS_FULL to the output of \
             tests/oracle/gen-page-parts-expected.ts --full"
        );
        return;
    };
    let ir_dir = PathBuf::from(std::env::var("LEAN_DOC_IR").unwrap_or_else(|_| DEFAULT_IR.into()));
    let lidx_path = PathBuf::from(
        std::env::var("LEAN_DOC_LINK_INDEX").unwrap_or_else(|_| DEFAULT_LINK_INDEX.into()),
    );

    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct Full {
        source_url: String,
        ir_declarations: usize,
        page_declarations: usize,
        headers: Vec<FullHeader>,
        decls: Vec<FullDecl>,
        frames: Vec<FullFrame>,
    }
    #[derive(Deserialize)]
    struct FullHeader {
        what: String,
        html: String,
    }
    #[derive(Deserialize)]
    struct FullDecl {
        what: String,
        header: String,
        html: String,
    }
    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct FullFrame {
        module: String,
        member_names: Vec<String>,
        head: String,
        header: String,
        nav: String,
    }

    let text = std::fs::read_to_string(&path).expect("LEAN_DOC_PAGE_PARTS_FULL is readable");
    let full: Full = serde_json::from_str(&text).expect("the --full file is valid");

    let tree = IrTree::open(&ir_dir).expect("the IR opens");
    let modules = tree.load_modules().expect("every module reads");
    let links = LinkIndex::read(&lidx_path).expect("the .lidx reads");
    let mut builder = NameIndex::builder();
    for dep in tree.load_dep_maps().expect("every dependency slice reads") {
        builder.dep_map(&dep);
    }
    for module in &modules {
        builder.module(module);
    }
    let index = builder.build(links);
    let code = CodeRenderer::new(&index);

    // `render.ts:2043-2048` — across **every** module, which is why it cannot
    // be folded into the per-module loop below.
    let suppressed: HashSet<&str> = modules
        .iter()
        .flat_map(|m| &m.declarations)
        .flat_map(|d| &d.members)
        .map(|m| m.name.as_str())
        .collect();

    let mut headers = 0usize;
    let mut decls = 0usize;
    let mut failures: Vec<String> = Vec::new();
    let note = |failures: &mut Vec<String>, what: &str, want: &str, got: &str| {
        if failures.len() < 10 {
            failures.push(format!(
                "{what}\n  want: {}\n  got:  {}",
                show(want),
                show(got)
            ));
        }
    };

    for (at, module) in modules.iter().enumerate() {
        let root = page_root(&module.module);
        let source_url = module_source_url(&full.source_url, &module.module);
        let names = module_decl_names(module);
        let page_links = PageLinks::new(&index, &root, &names);
        let docs = page_links.renderer();
        let renderer = DeclRenderer::new(module, &root, &source_url, code, &docs);

        // Every declaration's header, in IR order.
        for decl in &module.declarations {
            let want = full
                .headers
                .get(headers)
                .unwrap_or_else(|| panic!("the IR has more declarations than the oracle"));
            let what = format!("{} {} header", module.module, decl.name);
            assert_eq!(want.what, what, "the two sides walk the IR differently");
            let got = decl_header(decl, &module.module, &code);
            if got != want.html {
                note(&mut failures, &what, &want.html, &got);
            }
            headers += 1;
        }

        // Every declaration that gets a page entry, in page order.
        let mut page_decls: Vec<&Decl> = module
            .declarations
            .iter()
            .filter(|d| !suppressed.contains(d.name.as_str()))
            .collect();
        page_decls.sort_by_key(|d| (d.line, d.col, d.index));
        for decl in &page_decls {
            let want = full
                .decls
                .get(decls)
                .unwrap_or_else(|| panic!("the IR has more page entries than the oracle"));
            let what = format!("{} {}", module.module, decl.name);
            assert_eq!(want.what, what, "the two sides order the page differently");
            let header = decl_header(decl, &module.module, &code);
            if header != want.header {
                note(
                    &mut failures,
                    &format!("{what} (header)"),
                    &want.header,
                    &header,
                );
            }
            match renderer.decl_html(decl, &header) {
                Ok(html) if html == want.html => {}
                Ok(html) => note(&mut failures, &what, &want.html, &html),
                Err(e) => note(&mut failures, &what, &want.html, &e.to_string()),
            }
            decls += 1;
        }

        // The frame. The oracle writes one per module in index order, so the
        // position is the check that the two sides walk the same list.
        let frame = &full.frames[at];
        assert_eq!(frame.module, module.module, "the frames are out of step");
        let member_names: Vec<&str> = page_decls.iter().map(|d| d.name.as_str()).collect();
        assert_eq!(
            frame.member_names, member_names,
            "{}: the nav's page order differs",
            module.module
        );
        let got = head_html(&module.module, &root);
        if got != frame.head {
            note(
                &mut failures,
                &format!("{} head", module.module),
                &frame.head,
                &got,
            );
        }
        let got = page_header_html(&module.module, &root);
        if got != frame.header {
            note(
                &mut failures,
                &format!("{} header", module.module),
                &frame.header,
                &got,
            );
        }
        let got = internal_nav_html(
            &module.module,
            &root,
            &source_url,
            &module.imports,
            &member_names,
        );
        if got != frame.nav {
            note(
                &mut failures,
                &format!("{} nav", module.module),
                &frame.nav,
                &got,
            );
        }
    }

    eprintln!(
        "whole corpus: {headers} headers, {decls} declaration blocks, {} frames",
        modules.len()
    );
    assert!(
        failures.is_empty(),
        "{} differ:\n{}",
        failures.len(),
        failures.join("\n")
    );
    assert_eq!(headers, full.ir_declarations);
    assert_eq!(decls, full.page_declarations);
    assert_eq!(headers, 4_750, "the corpus changed size");
    assert_eq!(decls, 4_560, "the corpus changed size");
    assert_eq!(modules.len(), full.frames.len());
}

// ------------------------------------------------------------------- helpers

/// Renders a string so a failure names the code points rather than printing
/// control characters into the terminal, and truncates: a declaration block can
/// be 28 KB and the first difference is what matters.
fn show(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars().take(600) {
        if c == '\n' {
            out.push_str("\\n");
        } else if c == '\t' {
            out.push_str("\\t");
        } else if c.is_ascii_graphic() || c == ' ' || !c.is_control() {
            out.push(c);
        } else {
            out.push_str(&format!("<U+{:04X}>", c as u32));
        }
    }
    if s.chars().count() > 600 {
        out.push_str(" …");
    }
    out
}
