//! The two escapes that reach the generated bytes.
//!
//! Both are transcriptions of Lean functions, not of a general convention, and
//! both differ from the obvious Rust default (plan §7):
//!
//! - [`escape_html`] is `Html.escape` (doc-gen4's `ToHtmlFormat.lean`), which
//!   covers `& < > "` and nothing else. Every HTML-escaping crate also escapes
//!   `'`, and one of those extra characters in a page is one byte of mismatch.
//!   It **lives in `lean-doc-md`** and is re-exported here: the docstring
//!   renderer needs it too, and this crate depends on that one rather than the
//!   other way round. Re-exporting rather than copying is what keeps the
//!   differential test below covering the function the docstring renderer runs.
//! - [`lean_quote`] is Lean core's `String.quote`, which is *not*
//!   `format!("{:?}")`: it emits `\xNN` for the C0 controls and U+007F, and
//!   leaves everything else — including `\r` and every non-ASCII scalar — as
//!   the literal character.
//!
//! Ported from `experiments/stage7d/render.ts` (`escapeHtml` 330-341,
//! `leanQuote` 785-797), which is frozen.

use std::fmt::Write as _;

pub use lean_doc_md::{escape_html, escape_html_into};

/// Lean's `String.quote`, quotation marks included — the form the two
/// `<script>` constants of `baseHtmlGenerator` are written in.
pub fn lean_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    lean_quote_into(&mut out, s);
    out
}

/// [`lean_quote`] appending to an existing buffer.
pub fn lean_quote_into(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            // `Char.quoteCore`'s catch-all. `\r` lands here, not on an `\r`
            // escape, and the hex digits are lower case and zero-padded to two.
            _ if (c as u32) <= 31 || c as u32 == 127 => {
                let _ = write!(out, "\\x{:02x}", c as u32);
            }
            _ => out.push(c),
        }
    }
    out.push('"');
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quote_uses_lean_escapes() {
        assert_eq!(lean_quote("a\nb\tc\\d\"e"), r#""a\nb\tc\\d\"e""#);
        // `\r` is a control, so it goes through the hex branch.
        assert_eq!(lean_quote("\r"), r#""\x0d""#);
        assert_eq!(lean_quote("\u{0}\u{1f}\u{7f}"), r#""\x00\x1f\x7f""#);
        // U+0080 is a control in Unicode's sense but not in Lean's.
        assert_eq!(lean_quote("\u{80}"), "\"\u{80}\"");
        assert_eq!(lean_quote(""), "\"\"");
        assert_eq!(lean_quote("./"), "\"./\"");
    }
}
