//! The two escapes that reach the generated bytes.
//!
//! Both are transcriptions of Lean functions, not of a general convention, and
//! both differ from the obvious Rust default (plan §7):
//!
//! - [`escape_html`] is `Html.escape` (doc-gen4's `ToHtmlFormat.lean`), which
//!   covers `& < > "` and nothing else. Every HTML-escaping crate also escapes
//!   `'`, and one of those extra characters in a page is one byte of mismatch.
//! - [`lean_quote`] is Lean core's `String.quote`, which is *not*
//!   `format!("{:?}")`: it emits `\xNN` for the C0 controls and U+007F, and
//!   leaves everything else — including `\r` and every non-ASCII scalar — as
//!   the literal character.
//!
//! Ported from `experiments/stage7d/render.ts` (`escapeHtml` 330-341,
//! `leanQuote` 785-797), which is frozen.

use std::borrow::Cow;
use std::fmt::Write as _;

/// True for the four characters `Html.escape` rewrites. `'` is deliberately
/// absent.
const fn is_escapable(byte: u8) -> bool {
    matches!(byte, b'&' | b'<' | b'>' | b'"')
}

/// `Html.escape`: `&` `<` `>` `"` and nothing else.
///
/// Borrows when there is nothing to do, which is the common case for the
/// identifier and type fragments this runs over.
pub fn escape_html(s: &str) -> Cow<'_, str> {
    if !s.bytes().any(is_escapable) {
        return Cow::Borrowed(s);
    }
    let mut out = String::with_capacity(s.len() + 8);
    escape_html_into(&mut out, s);
    Cow::Owned(out)
}

/// [`escape_html`] appending to an existing buffer, for the page builder that
/// is concatenating anyway.
pub fn escape_html_into(out: &mut String, s: &str) {
    // The four characters are ASCII, and UTF-8 never encodes a non-ASCII scalar
    // with an ASCII byte, so scanning bytes cannot split a multi-byte scalar.
    let mut rest = s;
    while let Some(at) = rest.bytes().position(is_escapable) {
        out.push_str(&rest[..at]);
        out.push_str(match rest.as_bytes()[at] {
            b'&' => "&amp;",
            b'<' => "&lt;",
            b'>' => "&gt;",
            _ => "&quot;",
        });
        rest = &rest[at + 1..];
    }
    out.push_str(rest);
}

/// Lean's `String.quote`, quotation marks included — the form the two
/// `<script>` constants of `baseHtmlGenerator` are written in.
pub fn lean_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    lean_quote_into(&mut out, s);
    out
}

/// [`lean_quote`] appending to an existing buffer.
pub fn lean_quote_into(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            // `Char.quoteCore`'s catch-all. `\r` lands here, not on an `\r`
            // escape, and the hex digits are lower case and zero-padded to two.
            _ if (c as u32) <= 31 || c as u32 == 127 => {
                let _ = write!(out, "\\x{:02x}", c as u32);
            }
            _ => out.push(c),
        }
    }
    out.push('"');
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escapes_four_characters_and_no_others() {
        assert_eq!(
            escape_html("a & b < c > d \" e"),
            "a &amp; b &lt; c &gt; d &quot; e"
        );
        // The apostrophe is what a general-purpose escaper would also rewrite.
        assert_eq!(escape_html("Nat.succ'"), "Nat.succ'");
        assert_eq!(escape_html("a/b"), "a/b");
    }

    #[test]
    fn escape_borrows_when_it_can() {
        assert!(matches!(escape_html("∀ x, p x"), Cow::Borrowed(_)));
        assert!(matches!(escape_html("a<b"), Cow::Owned(_)));
    }

    #[test]
    fn escape_leaves_non_ascii_alone() {
        assert_eq!(escape_html("ℕ ∑ ≐ μ 𝒜 日本語"), "ℕ ∑ ≐ μ 𝒜 日本語");
    }

    #[test]
    fn quote_uses_lean_escapes() {
        assert_eq!(lean_quote("a\nb\tc\\d\"e"), r#""a\nb\tc\\d\"e""#);
        // `\r` is a control, so it goes through the hex branch.
        assert_eq!(lean_quote("\r"), r#""\x0d""#);
        assert_eq!(lean_quote("\u{0}\u{1f}\u{7f}"), r#""\x00\x1f\x7f""#);
        // U+0080 is a control in Unicode's sense but not in Lean's.
        assert_eq!(lean_quote("\u{80}"), "\"\u{80}\"");
        assert_eq!(lean_quote(""), "\"\"");
        assert_eq!(lean_quote("./"), "\"./\"");
    }
}
