//! Reading the dependency closure's `name -> module` map (`.lidx`).
//!
//! Ported from `experiments/stage7d/render.ts` (2067-2084), which is frozen.
//!
//! # Why the reader lives in the renderer
//!
//! Because the renderer is the only consumer. doc-gen4 resolves a docstring
//! autolink through `env.name2ModIdx`, which it has because it holds the whole
//! environment; this renderer holds none of it, so the map is an input. Nothing
//! else in the pipeline opens the file.
//!
//! **The producer moves; the format does not.** Today the map is derived from a
//! doc-gen4 site's `declarations/declaration-data.bmp`
//! (`experiments/stage7d/build-link-index.ts`), and M5 replaces that with a
//! scan of the environment the extractor already has loaded (plan 決定 4 / 決定
//! 5). That swap is confined to the writing side: what the renderer reads is
//! still a `.lidx`, so this module does not move with it.
//!
//! Passing the map is **not optional in the product**. The prototype's
//! full-generation path never passed `--link-index`, and the difference is 150
//! of 432 pages (34.7%) — plan 決定 4, 実測.
//!
//! # Format
//!
//! ```text
//! #lidx1                  format marker; any `#` line is ignored
//! @Mathlib.Order.Basic    a module name that is a link target in its own right
//! Mathlib.Order.Basic     a group header: the module the following names live in
//! \tMathlib.Order.le_refl  one declaration in that module
//! ```
//!
//! Line-oriented, split on `\n` only, first byte decides. Empty lines are
//! ignored, and an unknown leading byte is a group header — the prototype's
//! parser has no error path and neither does this one, so a garbled file
//! produces a map with garbage in it rather than a failure. Keeping that is
//! deliberate: the file is generated by this same toolchain, and diverging here
//! would be a behaviour change smuggled in with a port.

use std::collections::{HashMap, HashSet};
use std::path::Path;

/// The first line of a well-formed file. Not enforced — the prototype ignores
/// every `#` line — but worth naming, since M5 will write it.
pub const FORMAT_MARKER: &str = "#lidx1";

/// A `name -> defining module` map over a whole dependency closure.
///
/// Module names are interned: the target package's map is 258,760 entries over
/// 5,775 modules, so storing the module name per entry would be about 40x the
/// text it stands for.
#[derive(Debug, Default)]
pub struct LinkIndex {
    /// Group headers, in order of first appearance. Index 0 is the empty
    /// module, which entries before the first header fall into — as they do in
    /// the prototype, where the current module starts as `""`.
    modules: Vec<String>,
    module_ids: HashMap<String, u32>,
    names: HashMap<String, u32>,
    known_modules: HashSet<String>,
}

impl LinkIndex {
    /// Parses the file's text.
    pub fn parse(text: &str) -> Self {
        let mut index = Self {
            modules: vec![String::new()],
            ..Self::default()
        };
        let mut current = 0;
        for line in text.split('\n') {
            match line.as_bytes().first() {
                // A declaration in the current group. A repeated name takes the
                // later module, as `Map.prototype.set` does.
                Some(b'\t') => {
                    index.names.insert(line[1..].to_owned(), current);
                }
                Some(b'@') => {
                    index.known_modules.insert(line[1..].to_owned());
                }
                Some(b'#') => {}
                Some(_) => current = index.intern(line),
                None => {}
            }
        }
        index
    }

    /// Reads and parses a `.lidx` file.
    pub fn read(path: impl AsRef<Path>) -> std::io::Result<Self> {
        Ok(Self::parse(&std::fs::read_to_string(path)?))
    }

    fn intern(&mut self, module: &str) -> u32 {
        if let Some(&id) = self.module_ids.get(module) {
            return id;
        }
        let id = u32::try_from(self.modules.len()).expect("a .lidx has fewer than 4G modules");
        self.modules.push(module.to_owned());
        self.module_ids.insert(module.to_owned(), id);
        id
    }

    /// The module a declaration is defined in, if the map knows the name.
    pub fn module_of(&self, name: &str) -> Option<&str> {
        self.names
            .get(name)
            .map(|&id| self.modules[id as usize].as_str())
    }

    /// Whether a name is a module that is a link target in its own right — the
    /// `@` section, which doc-gen4 checks (`res.moduleNames.contains`) before
    /// falling back to the module-local search.
    pub fn is_known_module(&self, name: &str) -> bool {
        self.known_modules.contains(name)
    }

    /// The `@` section, for merging into the renderer's own set of modules.
    pub fn known_modules(&self) -> impl ExactSizeIterator<Item = &str> {
        self.known_modules.iter().map(String::as_str)
    }

    /// Declarations in the map.
    pub fn len(&self) -> usize {
        self.names.len()
    }

    pub fn is_empty(&self) -> bool {
        self.names.is_empty()
    }

    /// Distinct group headers, i.e. modules that define at least one of those
    /// declarations. Not the same number as [`LinkIndex::known_modules`]: the
    /// `@` section also lists modules that define nothing.
    pub fn module_count(&self) -> usize {
        self.modules.len() - 1
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "#lidx1\n\
        @Mathlib.Order.Basic\n\
        @Mathlib.Init\n\
        Mathlib.Order.Basic\n\
        \tMathlib.Order.le_refl\n\
        \tMathlib.Order.le_trans\n\
        Mathlib.Data.Nat\n\
        \tNat.succ\n";

    #[test]
    fn reads_groups_and_module_names() {
        let index = LinkIndex::parse(SAMPLE);
        assert_eq!(index.len(), 3);
        assert_eq!(index.module_count(), 2);
        assert_eq!(index.known_modules().len(), 2);
        assert_eq!(
            index.module_of("Mathlib.Order.le_refl"),
            Some("Mathlib.Order.Basic")
        );
        assert_eq!(index.module_of("Nat.succ"), Some("Mathlib.Data.Nat"));
        assert_eq!(index.module_of("Nat.pred"), None);
        assert!(index.is_known_module("Mathlib.Init"));
        // A group header is not automatically an `@` entry.
        assert!(!index.is_known_module("Mathlib.Data.Nat"));
    }

    #[test]
    fn empty_input_is_an_empty_map() {
        for text in ["", "\n", "#lidx1\n"] {
            let index = LinkIndex::parse(text);
            assert!(index.is_empty());
            assert_eq!(index.module_count(), 0);
        }
    }

    /// Names carry the same characters the rest of the port has to survive.
    #[test]
    fn non_ascii_names_round_trip() {
        let index = LinkIndex::parse("M.𝒜\n\tFoo.𝓧'\n\tℕ.add\n");
        assert_eq!(index.module_of("Foo.𝓧'"), Some("M.𝒜"));
        assert_eq!(index.module_of("ℕ.add"), Some("M.𝒜"));
    }

    /// The prototype's parser has no error path; a missing marker or a stray
    /// blank line changes nothing.
    #[test]
    fn blank_lines_and_a_missing_marker_are_tolerated() {
        let index = LinkIndex::parse("M\n\n\tA\n\n@N\n");
        assert_eq!(index.module_of("A"), Some("M"));
        assert!(index.is_known_module("N"));
        assert_eq!(index.module_count(), 1);
    }

    /// A repeated header is one module, and a repeated name takes the later
    /// one, as `Map.prototype.set` does.
    #[test]
    fn repeats_follow_the_prototype() {
        let index = LinkIndex::parse("M\n\tA\nN\n\tA\nM\n\tB\n");
        assert_eq!(index.module_count(), 2);
        assert_eq!(index.module_of("A"), Some("N"));
        assert_eq!(index.module_of("B"), Some("M"));
    }

    /// An entry before any header belongs to the empty module rather than to
    /// nothing, which is what the prototype's `let module = ""` produces.
    #[test]
    fn an_entry_before_the_first_header_has_an_empty_module() {
        let index = LinkIndex::parse("#lidx1\n\tA\nM\n\tB\n");
        assert_eq!(index.module_of("A"), Some(""));
        assert_eq!(index.module_count(), 1);
    }
}
