//! Every expectation in this file was produced by the frozen TypeScript
//! prototype, not by the Rust code it checks.
//!
//! `tests/data/global-expected.json` is generated by
//! `tests/oracle/gen-global-expected.ts`, which uses
//! `experiments/stage7h/global.ts` two ways at once. Regenerate with:
//!
//! ```text
//! deno run --allow-read --allow-write --allow-run \
//!   crates/lean-doc-global/tests/oracle/gen-global-expected.ts
//! deno run --allow-read --allow-write --allow-run \
//!   crates/lean-doc-global/tests/oracle/gen-global-expected.ts --check
//! ```
//!
//! # Two oracles, because one of them is blind
//!
//! `cases` run the prototype **as a program** over synthetic IR trees and record
//! the six files. That is the gate: byte equality with the prototype.
//!
//! `factCases` call `factsOf` / `autolinkTokens` / `headConst` **sliced out of
//! the same file**. [`lean_doc_global::ModuleFacts::tokens`] reaches no
//! artifact — it is the whole-package map delta's input, which is M2-b — so a
//! port that dropped tokens entirely would pass every byte comparison in the
//! first oracle. This one sees it.
//!
//! # What this file does **not** stand on
//!
//! The real corpus. That is [`artifacts_match_the_reference`] and
//! [`corpus_facts_match_the_prototype`], both env-gated, and
//! `tools/global-compare.sh`. The curated cases exist to reach the corners the
//! corpus has none of.
//!
//! # Fourteen of the thirty-seven branches never fire on the real corpus
//!
//! 【実測, `branchTotals`】 — among them every branch U1 depends on. The target
//! package has no name above the BMP anywhere: not one of 4,750 declarations,
//! not one of 533 dependency names, not one of 432 module names. All seven of
//! the prototype's argument-less `.sort()` calls therefore agree with a UTF-8
//! sort on all 1.9 MB of real output, and the only thing that says otherwise is
//! [`Case`] "names above the BMP".

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::PathBuf;

use lean_doc_global::{ARTIFACT_PATHS, GlobalOptions, ModuleFacts, build_global, facts_for};
use lean_doc_ir::IrTree;
use serde::{Deserialize, Serialize};

const FIXTURE: &str = include_str!("data/global-expected.json");

const DEFAULT_IR: &str = "/private/tmp/lean-doc-relay/w7h/base-ir";
const DEFAULT_REFERENCE: &str = "/private/tmp/lean-doc-relay/m2/ref-global";

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    oracle: String,
    ir_modules: usize,
    ir_declarations: usize,
    corpus_facts: CorpusFacts,
    /// `None` when the fixture was generated on a machine with no reference
    /// tree. Committed as `Some`.
    reference: Option<BTreeMap<String, Digest>>,
    /// How often each branch fires in one full run of the target package.
    branch_totals: BTreeMap<String, u64>,
    /// How many curated cases — of either kind — reach each branch.
    curated_branches: BTreeMap<String, u64>,
    /// The branches with a zero in `branch_totals`, as the generator listed
    /// them. Stored as well as derivable so a disagreement is itself a failure.
    never_fires: BTreeSet<String>,
    cases: Vec<Case>,
    fact_cases: Vec<FactCase>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CorpusFacts {
    modules: usize,
    bytes: usize,
    tokens: usize,
    fnv1a64: String,
    /// Module docstrings carrying the `doc` key `global.ts:152` reads. **Zero**,
    /// which is why the module docstring branch is dead — see
    /// [`module_docstrings_are_never_tokenised`].
    module_docs_with_doc_key: usize,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Digest {
    bytes: usize,
    fnv1a64: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Case {
    what: String,
    /// The counters this case's own IR makes fire, as the generator's profile
    /// function counted them.
    branches: Vec<String>,
    /// The IR tree as bytes, keyed by path under its root.
    ir: BTreeMap<String, String>,
    /// The six files the prototype wrote, keyed by path under the site root.
    artifacts: BTreeMap<String, String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct FactCase {
    what: String,
    branches: Vec<String>,
    note: Option<String>,
    content_hash: String,
    /// One module file, exactly as the prototype was handed it.
    module: String,
    facts: Facts,
}

/// [`ModuleFacts`] on the wire, in the key order `factsOf` returns it in. Also
/// what [`corpus_facts_match_the_prototype`] re-serialises to compare digests,
/// so the field order is load-bearing.
#[derive(Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
struct Facts {
    module: String,
    content_hash: String,
    imports: Vec<String>,
    tactics: usize,
    decls: Vec<(String, String)>,
    instances: Vec<(String, String)>,
    tokens: Vec<String>,
}

impl From<&ModuleFacts> for Facts {
    fn from(facts: &ModuleFacts) -> Self {
        Self {
            module: facts.module.clone(),
            content_hash: facts.content_hash.clone(),
            imports: facts.imports.clone(),
            tactics: facts.tactics,
            decls: facts.decls.clone(),
            instances: facts.instances.clone(),
            tokens: facts.tokens.clone(),
        }
    }
}

fn expected() -> Expected {
    serde_json::from_str(FIXTURE).expect("tests/data/global-expected.json is valid")
}

#[test]
fn fixture_is_the_prototypes_own_output() {
    let e = expected();
    assert!(e.oracle.contains("global.ts"), "{}", e.oracle);
    assert!(e.oracle.contains("run as a program"), "{}", e.oracle);
    assert!(e.oracle.contains("sliced out"), "{}", e.oracle);
    assert!(e.cases.len() >= 8, "only {} artifact cases", e.cases.len());
    assert!(
        e.fact_cases.len() >= 4,
        "only {} fact cases",
        e.fact_cases.len()
    );
}

/// The comparison this file exists for: the six artifacts, byte for byte.
#[test]
fn every_case_reproduces_the_prototypes_artifacts() {
    let e = expected();
    let mut failures = Vec::new();
    let mut compared = 0usize;
    for case in &e.cases {
        let work = TempDir::new(&case.what);
        let got = case.build(&work);
        if got != case.artifacts {
            failures.push(describe(&case.what, &case.artifacts, &got));
        }
        compared += case.artifacts.len();
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ from the prototype:\n{}",
        failures.len(),
        e.cases.len(),
        failures.join("\n")
    );
    assert_eq!(
        compared,
        e.cases.len() * ARTIFACT_PATHS.len(),
        "a case is missing one of the six artifacts"
    );
}

/// The other oracle: the per-module facts, including the tokens no artifact
/// carries.
#[test]
fn every_fact_case_reproduces_the_prototypes_facts() {
    let e = expected();
    for case in &e.fact_cases {
        let module: lean_doc_ir::ModuleFile = serde_json::from_str(&case.module)
            .unwrap_or_else(|e| panic!("{}: the module file parses: {e}", case.what));
        let got = Facts::from(&ModuleFacts::of(&module, &case.content_hash));
        assert_eq!(got, case.facts, "{}", case.what);
    }
}

/// The branch plan §5 says to transcribe rather than fix, pinned from both
/// sides: the corpus has no module docstring with the key the prototype reads,
/// and a curated module docstring full of linkable names still yields none.
#[test]
fn module_docstrings_are_never_tokenised() {
    let e = expected();
    assert_eq!(
        e.corpus_facts.module_docs_with_doc_key, 0,
        "a module docstring now carries the `doc` key `global.ts:152` reads; the transcription \
         in ModuleFacts::of is no longer a dead branch and the plan's §5 M2 entry is stale"
    );

    let case = e
        .fact_cases
        .iter()
        .find(|c| c.what.contains("module docstring"))
        .expect("a fact case covers the module docstring branch");
    let module: lean_doc_ir::ModuleFile =
        serde_json::from_str(&case.module).expect("the module file parses");
    assert!(
        module.module_docs.len() >= 2,
        "the case has to have module docstrings for their absence to mean anything"
    );
    assert!(
        module
            .module_docs
            .iter()
            .any(|doc| doc.text.contains('`') && doc.text.contains("](")),
        "the case's module docstrings have to contain names a fixed version would harvest"
    );
    let facts = ModuleFacts::of(&module, &case.content_hash);
    for token in &facts.tokens {
        assert!(
            !token.starts_with("Mod."),
            "{token:?} came from a module docstring: the transcription was 'fixed'"
        );
    }
    assert_eq!(facts.tokens, case.facts.tokens);
}

/// What the corpus is, pinned so a number quoted elsewhere traces to a run of
/// the generator rather than to a memory of one.
///
/// Every count is an event of **one full run** of the target package.
#[test]
fn the_corpus_numbers_are_what_was_measured() {
    let e = expected();
    assert_eq!(e.ir_modules, 432);
    assert_eq!(e.ir_declarations, 4_750);
    assert_eq!(
        e.branch_totals,
        BTreeMap::from(
            [
                // the facts
                ("moduleFacts", 432),
                ("moduleWithTactics", 0),
                ("tacticDocs", 0),
                ("moduleWithoutImports", 0),
                ("importOwn", 2_031),
                ("importForeign", 1_904),
                ("moduleDocDropped", 1_515),
                ("moduleDocWithCodeSpan", 759),
                ("declFacts", 4_750),
                ("declWithDoc", 3_394),
                ("declWithoutDoc", 1_356),
                ("declWithEmptyDoc", 0),
                ("docWithCodeSpan", 3_057),
                ("docWithLinkTarget", 1),
                ("tokensTotal", 21_825),
                ("tokenWithDot", 1_295),
                ("tokenEmptyString", 16),
                ("instanceDecl", 91),
                ("instanceWithHeadConst", 91),
                ("instanceWithoutHeadConst", 0),
                ("instanceHeadNotFirstSpan", 0),
                ("namedNonConstSpan", 0),
                // the derivation
                ("nameMapOverwrite", 0),
                ("instanceClassFirstSeen", 9),
                ("instanceClassAgain", 82),
                ("moduleImportedByNone", 1),
                ("depMapFiles", 3),
                ("depMapEntries", 533),
                ("depNameAlsoDeclared", 0),
                ("depNameOnly", 533),
                ("topLevelPagePath", 1),
                ("nestedPagePath", 431),
                ("moduleNameNeedsEscaping", 0),
                ("nameAboveBmp", 0),
                ("moduleNameAboveBmp", 0),
                ("runWithoutModules", 0),
                ("runWithoutDepMaps", 0),
            ]
            .map(|(k, n)| (k.to_owned(), n))
        ),
        "the branch profile of the corpus changed"
    );

    // Cross-checks between counters that have to agree by construction.
    assert_eq!(
        e.branch_totals["declWithDoc"] + e.branch_totals["declWithoutDoc"],
        e.ir_declarations as u64
    );
    assert_eq!(
        e.branch_totals["topLevelPagePath"] + e.branch_totals["nestedPagePath"],
        e.ir_modules as u64,
        "every module's page goes somewhere"
    );
    assert_eq!(
        e.branch_totals["instanceWithHeadConst"] + e.branch_totals["instanceWithoutHeadConst"],
        e.branch_totals["instanceDecl"]
    );
    assert_eq!(
        e.branch_totals["instanceClassFirstSeen"] + e.branch_totals["instanceClassAgain"],
        e.branch_totals["instanceWithHeadConst"],
        "every recorded instance lands under a class"
    );
    assert_eq!(
        e.branch_totals["depNameAlsoDeclared"] + e.branch_totals["depNameOnly"],
        e.branch_totals["depMapEntries"]
    );
    assert_eq!(e.corpus_facts.modules, e.ir_modules);
    assert_eq!(
        e.corpus_facts.tokens as u64, e.branch_totals["tokensTotal"],
        "the digest and the profile were taken from different runs"
    );
    // `a.` really does occur: 16 tokens of the corpus are the empty string,
    // which only `push`'s unconditional last component can produce.
    assert!(e.branch_totals["tokenEmptyString"] > 0);
}

/// The fourteen branches no module of the target package reaches, and the fact
/// that the curated cases do reach them.
#[test]
fn the_curated_cases_cover_what_the_package_does_not() {
    let e = expected();
    let never: BTreeSet<String> = e
        .branch_totals
        .iter()
        .filter(|(_, n)| **n == 0)
        .map(|(k, _)| k.clone())
        .collect();
    assert_eq!(
        never, e.never_fires,
        "the generator and the totals disagree about which branches are dead"
    );
    assert_eq!(
        never,
        BTreeSet::from(
            [
                // U1. Not one name in the package is above the BMP, so a UTF-8
                // sort in any of the seven places is invisible to all 1.9 MB.
                "nameAboveBmp",
                "moduleNameAboveBmp",
                // The package declares no tactics, so `tactics.html`'s first
                // count is always the literal it looks like.
                "moduleWithTactics",
                "tacticDocs",
                // Every instance's printed type has a constant span, and it is
                // always the first one in the array.
                "instanceWithoutHeadConst",
                "instanceHeadNotFirstSpan",
                // The extractor names kind-1 spans and nothing else, so
                // `head_const`'s kind test is load-bearing only in theory.
                "namedNonConstSpan",
                // Every name is declared once, and no dependency slice names
                // something the package declares.
                "nameMapOverwrite",
                "depNameAlsoDeclared",
                // Shapes the extractor never produced here.
                "moduleWithoutImports",
                "moduleNameNeedsEscaping",
                "declWithEmptyDoc",
                // Degenerate runs.
                "runWithoutModules",
                "runWithoutDepMaps",
            ]
            .map(str::to_owned)
        ),
        "which branches the target package never reaches has changed"
    );
    for branch in &never {
        assert!(
            e.curated_branches.get(branch).copied().unwrap_or(0) > 0,
            "{branch} fires nowhere in the corpus and nowhere in the curated cases either"
        );
    }
    let all: BTreeSet<&String> = e.branch_totals.keys().collect();
    let curated: BTreeSet<&String> = e
        .curated_branches
        .iter()
        .filter(|(_, n)| **n > 0)
        .map(|(k, _)| k)
        .collect();
    assert_eq!(all, curated, "the curated cases stopped covering a branch");

    // `curatedBranches` is a tally of the per-case lists, so recompute it: a
    // summary that is not what it summarises is how a coverage claim rots.
    let mut tally: BTreeMap<String, u64> = BTreeMap::new();
    let per_case = e
        .cases
        .iter()
        .map(|case| &case.branches)
        .chain(e.fact_cases.iter().map(|case| &case.branches));
    for branches in per_case {
        for branch in branches {
            assert!(
                e.branch_totals.contains_key(branch),
                "case claims {branch}, which is not a counter"
            );
            *tally.entry(branch.clone()).or_default() += 1;
        }
    }
    assert_eq!(
        tally, e.curated_branches,
        "the tally and the per-case lists disagree"
    );
}

/// The sample has to keep reaching every shape, read off the **fixture's own
/// bytes** — which came from the prototype — rather than off anything this
/// crate produced.
#[test]
fn the_sample_reaches_every_shape() {
    let e = expected();
    let bmp = |what: &str, p: &dyn Fn(&str) -> bool| {
        any_artifact(&e.cases, ARTIFACT_PATHS[0], what, p);
    };
    let names = |what: &str, p: &dyn Fn(&str) -> bool| {
        any_artifact(&e.cases, ARTIFACT_PATHS[1], what, p);
    };
    let navbar = |what: &str, p: &dyn Fn(&str) -> bool| {
        any_artifact(&e.cases, ARTIFACT_PATHS[2], what, p);
    };
    let tactics = |what: &str, p: &dyn Fn(&str) -> bool| {
        any_artifact(&e.cases, ARTIFACT_PATHS[3], what, p);
    };

    // U1: 𝒜 (U+1D49C) has to come out **before** ﬀ (U+FB00) everywhere.
    let astral_first = |body: &str| match (body.find('\u{1D49C}'), body.find('\u{FB00}')) {
        (Some(astral), Some(ligature)) => astral < ligature,
        _ => false,
    };
    bmp(
        "a name above the BMP sorted before one inside it",
        &astral_first,
    );
    names(
        "a name above the BMP sorted before one inside it",
        &astral_first,
    );
    navbar(
        "a module name above the BMP sorted before one inside it",
        &astral_first,
    );

    bmp("no declarations at all", &|body| {
        body.starts_with("{\"declarations\":{},")
    });
    bmp("an instance list", &|body| {
        body.contains("\"instances\":{\"Cls.B\":[\"Pkg.Inst.alsoB\",\"Pkg.Inst.reordered\"]")
    });
    bmp("an instance dropped for want of a head constant", &|body| {
        body.contains("Pkg.Inst.noConst") && !body.contains("[\"Pkg.Inst.noConst\"]")
    });
    bmp("an importedBy list", &|body| {
        body.contains("\"importedBy\":[\"Pkg.Deep.Down.Here\"]")
    });
    bmp("a duplicated name resolved to the later module", &|body| {
        body.contains(
            "\"Pkg.shared\":{\"docLink\":\"./Pkg/Second.html#Pkg.shared\",\"kind\":\"def\"}",
        )
    });
    names("a declaration beating a dependency slice", &|body| {
        body.contains("\"Shared.name\":\"Pkg.One\"")
    });
    names("a later dependency slice beating an earlier one", &|body| {
        body.contains("\"Dep.only\":\"Dep2.Wins\"")
    });
    // The apostrophe stays raw: `Html.escape` does not touch it, and every
    // general-purpose HTML escaper does.
    navbar("a module name that needs escaping", &|body| {
        body.contains(
            "<li><a href=\"./Pkg/A&lt;B&amp;C&quot;D'E.html\">Pkg.A&lt;B&amp;C&quot;D'E</a></li>",
        )
    });
    navbar("no modules at all", &|body| body.contains("<ul></ul>"));
    tactics("a package that declares tactics", &|body| {
        body.contains("(3 tactic docstrings across 3 modules)")
    });
    tactics("no modules at all", &|body| {
        body.contains("(0 tactic docstrings across 0 modules)")
    });

    // The fact cases' own corners.
    let tokens: Vec<&String> = e
        .fact_cases
        .iter()
        .flat_map(|c| c.facts.tokens.iter())
        .collect();
    assert!(
        tokens.iter().any(|t| t.is_empty()),
        "no fact case has the empty token a part ending in a dot produces"
    );
    assert!(
        tokens.iter().any(|t| *t == "Bar.baz"),
        "no fact case tokenises a markdown link target"
    );
    assert!(
        e.fact_cases.iter().any(|c| c.note.is_some()),
        "the recorded disagreement lost its note"
    );
}

/// This crate's URL-path rule and the renderer's filesystem one have to be the
/// same rule: `declaration-data.bmp` links to pages the renderer wrote, and a
/// disagreement is 4,750 dead links that no byte comparison of either side
/// notices.
#[test]
fn page_paths_agree_with_the_renderers() {
    for module in [
        "Pkg",
        "Pkg.One",
        "Pkg.A.B.C.D",
        "InformationTheory.Shannon.TimeBandLimiting.Count",
        "Pkg.\u{1D49C}",
        "Pkg.A<B&C\"D",
    ] {
        assert_eq!(
            lean_doc_global::page_path(module),
            lean_doc_render::page_path(module).to_string_lossy(),
            "{module}"
        );
    }
}

/// The six artifacts of the target package, against the files the prototype
/// wrote. Skipped unless the reference tree is present.
///
/// The same comparison `tools/global-compare.sh` makes.
#[test]
fn artifacts_match_the_reference() {
    let e = expected();
    let recorded = e
        .reference
        .as_ref()
        .expect("the committed fixture pins the real artifacts");
    // Pinned whether or not the corpus is on this machine, so the numbers in
    // the report have a home.
    assert_eq!(
        recorded["declarations/declaration-data.bmp"].bytes,
        1_216_017
    );
    assert_eq!(recorded["declarations/name-map.json"].bytes, 602_729);
    assert_eq!(recorded["navbar.html"].bytes, 57_949);
    assert_eq!(recorded["tactics.html"].bytes, 243);
    assert_eq!(recorded["references.bib"].bytes, 0);
    assert_eq!(recorded["references.html"].bytes, 186);

    let reference = PathBuf::from(
        std::env::var("LEAN_DOC_REFERENCE_GLOBAL").unwrap_or_else(|_| DEFAULT_REFERENCE.into()),
    );
    let ir = PathBuf::from(std::env::var("LEAN_DOC_IR").unwrap_or_else(|_| DEFAULT_IR.into()));
    if !reference.is_dir() || !ir.is_dir() {
        eprintln!("skipping: no corpus at {}", ir.display());
        return;
    }

    let work = TempDir::new("reference");
    let summary = build_global(&GlobalOptions {
        ir: &ir,
        out: &work.path,
    })
    .expect("the corpus builds");
    assert_eq!(summary.modules, e.ir_modules);
    assert_eq!(summary.declarations, e.ir_declarations);
    assert_eq!(
        summary.dependency_names as u64,
        e.branch_totals["depMapEntries"]
    );
    assert_eq!(
        summary.instance_classes as u64,
        e.branch_totals["instanceClassFirstSeen"]
    );
    assert_eq!(summary.tactic_docs, 0);

    for path in ARTIFACT_PATHS {
        let want = fs::read(reference.join(path)).expect("the reference artifact reads");
        let got = fs::read(work.path.join(path)).expect("the artifact was written");
        assert_eq!(
            recorded[path].bytes,
            want.len(),
            "{path}: the reference tree is not the one the fixture was taken from"
        );
        assert_eq!(fnv1a64(&want), recorded[path].fnv1a64, "{path}");
        assert_eq!(
            got.len(),
            want.len(),
            "{path}: {} bytes against the prototype's {}",
            got.len(),
            want.len()
        );
        assert!(
            got == want,
            "{path} differs from the prototype at byte {}",
            got.iter()
                .zip(&want)
                .position(|(a, b)| a != b)
                .unwrap_or(got.len())
        );
    }
}

/// The per-module facts over the whole corpus, against the prototype's own
/// `factsOf`. Skipped unless the IR is present.
///
/// This is what checks [`ModuleFacts::tokens`] on 3,394 real docstrings rather
/// than on four curated ones. The digest is FNV-1a 64 over the same canonical
/// JSON both sides emit; the two counts beside it are what a digest cannot say
/// when it disagrees.
#[test]
fn corpus_facts_match_the_prototype() {
    let e = expected();
    let ir = PathBuf::from(std::env::var("LEAN_DOC_IR").unwrap_or_else(|_| DEFAULT_IR.into()));
    if !ir.is_dir() {
        eprintln!("skipping: no corpus at {}", ir.display());
        return;
    }
    let tree = IrTree::open(&ir).expect("the corpus opens");
    let facts = facts_for(&tree).expect("the corpus reads");
    assert_eq!(facts.len(), e.corpus_facts.modules);

    let lines: Vec<String> = facts
        .iter()
        .map(|facts| serde_json::to_string(&Facts::from(facts)).expect("the facts serialise"))
        .collect();
    let text = lines.join("\n");
    let tokens: usize = facts.iter().map(|facts| facts.tokens.len()).sum();
    assert_eq!(tokens, e.corpus_facts.tokens, "the token count moved");
    assert_eq!(
        text.len(),
        e.corpus_facts.bytes,
        "the serialised facts are a different size than the prototype's"
    );
    assert_eq!(
        fnv1a64(text.as_bytes()),
        e.corpus_facts.fnv1a64,
        "the facts differ from the prototype's somewhere in {} bytes",
        text.len()
    );
}

// ------------------------------------------------------------------- helpers

/// At least one case's copy of `path` satisfies `predicate`.
fn any_artifact(cases: &[Case], path: &str, what: &str, predicate: &dyn Fn(&str) -> bool) {
    assert!(
        cases
            .iter()
            .filter_map(|case| case.artifacts.get(path))
            .any(|body| predicate(body)),
        "no {path} with {what}"
    );
}

impl Case {
    /// Writes the case's IR into `work`, builds the artifacts, and reads the
    /// six files back.
    fn build(&self, work: &TempDir) -> BTreeMap<String, String> {
        let ir = work.path.join("ir");
        for (name, text) in &self.ir {
            let path = ir.join(name);
            fs::create_dir_all(path.parent().expect("every IR file is under the root"))
                .expect("the temporary tree is writable");
            fs::write(&path, text).expect("the temporary tree is writable");
        }
        let site = work.path.join("site");
        build_global(&GlobalOptions {
            ir: &ir,
            out: &site,
        })
        .unwrap_or_else(|e| panic!("{}: {e}", self.what));

        ARTIFACT_PATHS
            .iter()
            .map(|path| {
                let body = fs::read_to_string(site.join(path))
                    .unwrap_or_else(|e| panic!("{}: {path}: {e}", self.what));
                ((*path).to_owned(), body)
            })
            .collect()
    }
}

/// FNV-1a 64, the same ten lines the generator has. A staleness check, not a
/// security property.
fn fnv1a64(bytes: &[u8]) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in bytes {
        hash = (hash ^ u64::from(*byte)).wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}

fn describe(what: &str, want: &BTreeMap<String, String>, got: &BTreeMap<String, String>) -> String {
    let mut lines = vec![what.to_owned()];
    for path in want.keys().chain(got.keys()).collect::<BTreeSet<_>>() {
        match (want.get(path), got.get(path)) {
            (Some(a), Some(b)) if a == b => {}
            (Some(a), Some(b)) => {
                let at = a
                    .bytes()
                    .zip(b.bytes())
                    .position(|(x, y)| x != y)
                    .unwrap_or_else(|| a.len().min(b.len()));
                let from = at.saturating_sub(80);
                lines.push(format!(
                    "  {path} differs at byte {at}\n    want: …{}\n    got:  …{}",
                    &a[floor_char(a, from)..floor_char(a, (at + 120).min(a.len()))],
                    &b[floor_char(b, from)..floor_char(b, (at + 120).min(b.len()))],
                ));
            }
            (Some(_), None) => lines.push(format!("  {path} was not written")),
            (None, Some(_)) => lines.push(format!("  {path} should not exist")),
            (None, None) => unreachable!(),
        }
    }
    lines.join("\n")
}

/// The nearest char boundary at or below `at`, so slicing an artifact for a
/// failure message cannot itself panic.
fn floor_char(s: &str, mut at: usize) -> usize {
    while at > 0 && !s.is_char_boundary(at) {
        at -= 1;
    }
    at
}

/// A directory that removes itself. Hand-rolled rather than a dependency: it is
/// ten lines and the workspace has no other use for one.
struct TempDir {
    path: PathBuf,
}

impl TempDir {
    fn new(what: &str) -> Self {
        use std::sync::atomic::{AtomicU32, Ordering};
        static NEXT: AtomicU32 = AtomicU32::new(0);
        let slug: String = what
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
            .take(40)
            .collect();
        let path = std::env::temp_dir().join(format!(
            "lean-doc-global-{}-{}-{slug}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).expect("the temporary directory is creatable");
        Self { path }
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.path);
    }
}
