//! Every answer in this file was produced by **doc-gen4**, not by the Rust code
//! it checks.
//!
//! `tests/data/docgen4-expected.json` is generated by
//! `tests/oracle/gen-docgen4-expected.ts`, which runs `docStringToHtml` under
//! `lake env lean` in the measurement target and prints the bytes. The corpus is
//! every docstring in that package's IR plus hand-written cases for the corners
//! it does not contain. Regenerate with:
//!
//! ```text
//! deno run --allow-read --allow-write --allow-run --allow-env \
//!   crates/lean-doc-md/tests/oracle/gen-docgen4-expected.ts
//! ... --check      # verify the committed file
//! ... --full PATH  # also write every case, for [`the_whole_corpus`]
//! ```
//!
//! # Why the whole corpus can be compared, auto-links included
//!
//! doc-gen4 resolves names against the environment, so a naive run of it would
//! produce anchors this milestone step cannot produce, and the comparison would
//! have to exclude every docstring mentioning a documented name — which is most
//! of them. It does not have to: `nameToLink?` reads *only* the `AnalyzerResult`
//! in its context, and the dumper hands it the empty one. Every lookup then
//! misses, which is precisely [`NoLinks`]. So nothing is excluded and nothing is
//! normalised away — 4,987 of 4,989 cases are compared byte for byte, the two
//! exceptions being the inputs that kill the Lean side outright
//! ([`the_inputs_that_kill_doc_gen4_here`]).
//!
//! What this does *not* check is `nameToLink?` itself. That is the next
//! milestone step's, and it will need an oracle run with a real environment.

use lean_doc_md::{NoLinks, Renderer};
use serde::Deserialize;

const FIXTURE: &str = include_str!("data/docgen4-expected.json");

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    /// How the answers were produced, for the report a failure prints.
    oracle: String,
    lean_toolchain: String,
    doc_gen4_rev: Option<String>,
    /// How many distinct docstrings the target package's IR holds.
    ir_docstrings: usize,
    /// The `getRoot` values the corpus was rendered at.
    roots: Vec<String>,
    cases: Vec<Case>,
    /// The inputs that kill the Lean side, recorded rather than expected.
    crashes_doc_gen4: Vec<Crasher>,
}

#[derive(Deserialize)]
struct Case {
    /// Where the docstring came from: a declaration name, or `curated: …`.
    what: String,
    /// The `getRoot` this case was rendered at.
    root: String,
    md: String,
    /// doc-gen4's bytes.
    html: String,
}

#[derive(Deserialize)]
struct Crasher {
    what: String,
    md: String,
}

fn expected() -> Expected {
    serde_json::from_str(FIXTURE).expect("tests/data/docgen4-expected.json is valid")
}

/// Renders an input so a failure names the code points rather than printing
/// control characters into the terminal.
fn show(s: &str) -> String {
    let head: String = s
        .chars()
        .take(200)
        .map(|c| {
            if c.is_ascii_graphic() || c == ' ' {
                c.to_string()
            } else {
                format!("<U+{:04X}>", c as u32)
            }
        })
        .collect();
    if s.chars().count() > 200 {
        format!("{head}...")
    } else {
        head
    }
}

/// The first byte at which two strings differ, with a window around it — a
/// whole-page diff of a 4 KB docstring is unreadable.
fn first_difference(want: &str, got: &str) -> String {
    let at = want
        .as_bytes()
        .iter()
        .zip(got.as_bytes())
        .position(|(a, b)| a != b)
        .unwrap_or_else(|| want.len().min(got.len()));
    let from = at.saturating_sub(40);
    let window = |s: &str| {
        let to = (at + 40).min(s.len());
        let from = from.min(s.len());
        show(&String::from_utf8_lossy(&s.as_bytes()[from..to]))
    };
    format!(
        "byte {at} of {} (doc-gen4) / {} (here)\n  doc-gen4: …{}…\n  here:     …{}…",
        want.len(),
        got.len(),
        window(want),
        window(got)
    )
}

/// Compares one case, returning a description of the disagreement.
fn check(case: &Case) -> Option<String> {
    let got = Renderer::new(&case.root, &NoLinks).docstring(&case.md);
    if got == case.html {
        return None;
    }
    Some(format!(
        "{} (root {:?})\n  input: {}\n  {}",
        case.what,
        case.root,
        show(&case.md),
        first_difference(&case.html, &got)
    ))
}

#[test]
fn the_fixture_is_doc_gen4s_own_output() {
    let e = expected();
    assert!(e.oracle.contains("docStringToHtml"), "{}", e.oracle);
    assert_eq!(e.lean_toolchain, "leanprover/lean4:v4.31.0");
    assert_eq!(
        e.doc_gen4_rev.as_deref(),
        Some("0bc516c1b9db83658d6475c40d9b1ed71219b921"),
        "the doc-gen4 the reference tree was built with"
    );
    // 実測: the target package's IR holds this many distinct docstrings.
    assert_eq!(e.ir_docstrings, 4_858);
    // The root reaches the bytes, so more than one of them has to be exercised.
    assert_eq!(e.roots, ["./", ".././", "../.././"]);
    assert!(e.cases.len() >= 300, "only {} cases", e.cases.len());
    assert_eq!(e.crashes_doc_gen4.len(), 2);
}

#[test]
fn every_case_matches_doc_gen4() {
    let e = expected();
    let failures: Vec<String> = e.cases.iter().filter_map(check).collect();
    assert!(
        failures.is_empty(),
        "{} of {} cases disagree with doc-gen4:\n{}",
        failures.len(),
        e.cases.len(),
        failures
            .iter()
            .take(10)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// Where the generator's `--full` file was left on the machine these numbers
/// were measured on. Megabytes of generated JSON, so it lives outside the
/// repository like the parser's does.
const DEFAULT_FULL: &str = "/private/tmp/lean-doc-relay/m1c/docgen4-full.json";

/// The whole corpus, from the generator's `--full` file.
///
/// `#[ignore]`d rather than silently skipped: that file is not in this
/// repository, `cargo test` has to pass where the target package does not
/// exist, and a run that reports this as ignored says out loud that the other
/// 4,414 cases were not checked.
#[test]
#[ignore = "corpus: needs LEAN_DOC_DOCGEN4_FULL (tools/corpus-gate.sh)"]
fn the_whole_corpus() {
    let path = std::env::var("LEAN_DOC_DOCGEN4_FULL").unwrap_or_else(|_| DEFAULT_FULL.to_owned());
    assert!(
        std::path::Path::new(&path).is_file(),
        "no --full file at {path}: set LEAN_DOC_DOCGEN4_FULL, or regenerate with \
         tests/oracle/gen-docgen4-expected.ts --full, or run this test through \
         tools/corpus-gate.sh, which is the only thing that should be asking for it"
    );
    let text = std::fs::read_to_string(&path).expect("the --full file");
    let full: Expected = serde_json::from_str(&text).expect("a --full file");
    assert!(
        full.cases.len() > 4_000,
        "{path} holds only {} cases",
        full.cases.len()
    );
    let failures: Vec<String> = full.cases.iter().filter_map(check).collect();
    assert!(
        failures.is_empty(),
        "{} of {} cases disagree with doc-gen4:\n{}",
        failures.len(),
        full.cases.len(),
        failures
            .iter()
            .take(10)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
    eprintln!("{} cases agreed with doc-gen4", full.cases.len());
}

/// The committed sample has to keep reaching every branch of the renderer, or
/// a machine without the target package is checking less than it looks.
///
/// The markers are on the *output* side on purpose: they are what a wrong
/// branch would change. `heading id` and `find/?pattern=` are the two pieces of
/// this milestone step that are not md4c's and not a plain tag.
#[test]
fn the_sample_still_covers_the_output() {
    let e = expected();
    let all: String = e.cases.iter().map(|c| c.html.as_str()).collect();
    for marker in [
        "<p>",
        "<ul>",
        "<ol>",
        "<ol start=\"",
        "<li>",
        "<hr>\n",
        "<h1 ",
        "<h6 ",
        "class=\"markdown-heading\"",
        "class=\"hover-link\"",
        "<pre><code>",
        "<pre><code class=\"language-",
        "<blockquote>",
        "<table><thead><tr><th>",
        "<tbody><tr><td>",
        "<em>",
        "<strong>",
        "<del>",
        "<br>\n",
        "<code>",
        "<img src=\"",
        " title=\"",
        "<a href=\"",
        "find/?pattern=",
        "$",
        "$$",
        "<input type=\"checkbox\" checked=\"\" disabled=\"\">",
        "<input type=\"checkbox\" disabled=\"\">",
        "&amp;",
        "&lt;",
        "&quot;",
        "\u{FFFD}",
    ] {
        assert!(
            all.contains(marker),
            "nothing in the sample produces {marker:?}"
        );
    }
    // The three doc-gen4 cannot emit under `MD_FLAG_NOHTML` and the two flags
    // it leaves off. Their appearance would mean the dialect had drifted.
    for never in ["<u>", "<x-wikilink"] {
        assert!(
            !all.contains(never),
            "{never:?} appeared; the dialect drifted"
        );
    }
}

/// The inputs that kill doc-gen4, and what this crate does instead.
///
/// Both are undefined behaviour on the Lean side (see `tests/md4lean.rs`), so
/// there are no bytes to match; what is pinned is that neither crashes us and
/// that both still render something.
#[test]
fn the_inputs_that_kill_doc_gen4_here() {
    for crasher in expected().crashes_doc_gen4 {
        let got = Renderer::new("./", &NoLinks).docstring(&crasher.md);
        assert!(!got.is_empty(), "{}", crasher.what);
    }
    // A NUL inside a fenced code block: U+FFFD, then the byte md4c re-reports.
    assert_eq!(
        Renderer::new("./", &NoLinks).docstring("```\na\0b\n```\n"),
        "<pre><code>a\u{FFFD}\0b\n</code></pre>"
    );
    // A table with a header and no body rows: an empty `<tbody>`.
    assert_eq!(
        Renderer::new("./", &NoLinks).docstring("| a | b |\n|---|---|\n"),
        "<table><thead><tr><th>a</th><th>b</th></tr></thead><tbody></tbody></table>"
    );
}
