#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run --allow-env
// gen-docgen4-linked-expected.ts -- produce the expected HTML for
// `tests/docgen4_linked.rs` by running *doc-gen4 itself* with a name map that
// is not empty.
//
// WHY THIS FILE EXISTS
// --------------------
// The primary oracle for autolink resolution is the frozen prototype
// (`gen-autolink-expected.ts`): plan §5 says so, because `render.ts`'s
// `nameToLink` is the function that scores 439/439 and doc-gen4's `nameToLink?`
// is a *different* function. But "the prototype is the target" is not the same
// as "the prototype is always right", and M1-c's earlier doc-gen4 comparison ran
// with every lookup missing -- so nothing had ever asked doc-gen4 what a
// *resolved* docstring looks like.
//
// This script asks. It fills `AnalyzerResult.name2ModIdx` and `.moduleNames`,
// which is all `nameToLink?`'s first three branches read, and compares. It
// found one real disagreement on the first run: the prototype auto-links a code
// span inside an `<a>` and doc-gen4 does not (`inLink`, `DocString.lean:264`
// vs `render.ts:1622`). No docstring of the target package reaches it 【実測:
// 0 of 4,858】, but the port follows doc-gen4, so the expectation has to come
// from doc-gen4.
//
// THE AGREEMENT ZONE
// ------------------
// The two specifications genuinely differ in three places, and this script
// keeps all three out of the corpus rather than hiding them:
//
//   * private names -- `isPrivateName` (mangling) vs a `_private.` prefix test;
//   * auto-generated eliminators -- doc-gen4 links `Foo.rec` to `Foo`;
//   * the "similar name in this module" branch -- doc-gen4 needs `moduleInfo`,
//     which cannot be built here, so `currentName := none` disables it and the
//     Rust side is rendered with an empty declaration list to match.
//
// Names that would need `Name.toString` to escape them (guillemets) are also
// left out: `declNameToLink` re-prints the `Name`, the prototype echoes the
// string it was given, and the two are only equal when the name round-trips.
//
// npm/node are broken in this environment; this must run under deno, and the
// oracle needs the measurement target (that is where doc-gen4 is built).
//
// usage:
//   deno run --allow-read --allow-write --allow-run --allow-env \
//     crates/lean-doc-render/tests/oracle/gen-docgen4-linked-expected.ts
//   ... --check                     fail if the committed file is stale
//   ... --target DIR --ir DIR --link-index FILE

const FIXTURE = new URL("../data/docgen4-linked-expected.json", import.meta.url);
const DUMPER = new URL("dump-html-linked.lean", import.meta.url);
const RENDER_TS = new URL("../../../../experiments/stage7d/render.ts", import.meta.url);

const DEFAULT_TARGET = "/Users/haruka/dev/lean-projects";
const DEFAULT_IR = "/private/tmp/lean-doc-relay/w7h/base-ir";
const DEFAULT_LINK_INDEX = "/private/tmp/lean-doc-relay/w7c/linkindex/link-index.lidx";

/** How many real docstrings to take. Kept small: the fixture is committed. */
const REAL_CASES = 120;
const COMPACT_CHARS = 700;

/** `isAutoGeneratedSuffix` (`DocString.lean:28-30`). */
const AUTO_SUFFIXES = new Set([
  "rec",
  "recOn",
  "casesOn",
  "noConfusion",
  "noConfusionType",
  "below",
  "brecOn",
]);

// ---------------------------------------------------- slicing render.ts

const renderLines = (await Deno.readTextFile(RENDER_TS)).split("\n");
const slice = (from: number, to: number) => renderLines.slice(from - 1, to).join("\n");

const RANGES = {
  escapeHtml: { from: 331, to: 341, head: "function escapeHtml(" },
  links: { from: 385, to: 393, head: "function moduleLink(" },
  privatePrefix: { from: 415, to: 415, head: "const PRIVATE_PREFIX =" },
  docstrings: { from: 932, to: 1672, head: "function nameToLink(" },
} as const;

for (const [what, { from, to, head }] of Object.entries(RANGES)) {
  if (!slice(from, to).startsWith(head)) {
    console.error(`render.ts:${from}-${to} no longer starts with ${JSON.stringify(head)} (${what})`);
    Deno.exit(3);
  }
}
const at = (k: keyof typeof RANGES) => slice(RANGES[k].from, RANGES[k].to);

const MODULE_SOURCE = [
  "export const known = new Map<string, string>();",
  "export const linkIndex = new Map<string, string>();",
  "const abl = (_name: string) => false;",
  "const pageStats = { autolinkAttempts: 0, autolinkResolved: 0 };",
  "const T = { docstring: 0 };",
  at("privatePrefix"),
  at("escapeHtml"),
  at("links"),
  at("docstrings"),
  "export { renderDocString, isNameLit, pageRoot };",
].join("\n\n");

const prototype = await import(
  `data:text/typescript;charset=utf-8,${encodeURIComponent(MODULE_SOURCE)}`
) as {
  renderDocString(
    md: string,
    ctx: { root: string; moduleDeclNames: string[]; knownModules: Set<string> },
  ): string;
  isNameLit(s: string): boolean;
  pageRoot(module: string): string;
  known: Map<string, string>;
  linkIndex: Map<string, string>;
};

// -------------------------------------------------------------------- inputs

const args = Deno.args;
const flag = (name: string, fallback: string | null = null) => {
  const i = args.indexOf(name);
  return i >= 0 && i + 1 < args.length ? args[i + 1] : fallback;
};
const target = flag("--target", DEFAULT_TARGET)!;
const ir = flag("--ir", DEFAULT_IR)!;
const linkIndexPath = flag("--link-index", DEFAULT_LINK_INDEX)!;
const check = args.includes("--check");

// deno-lint-ignore no-explicit-any
const readJson = async (path: string): Promise<any> => JSON.parse(await Deno.readTextFile(path));

const fullKnown = new Map<string, string>();
const fullLinkIndex = new Map<string, string>();
const fullKnownModules = new Set<string>();

const index = await readJson(`${ir}/index.json`);
for (const dep of index.dependencyMaps) {
  const map = await readJson(`${ir}/${dep.file}`);
  for (const [n, m] of Object.entries(map.declarations as Record<string, string>)) {
    fullKnown.set(n, m);
  }
}
// deno-lint-ignore no-explicit-any
const irModules: any[] = [];
for (const entry of index.modules) {
  const mod = await readJson(`${ir}/${entry.file}`);
  irModules.push(mod);
  fullKnownModules.add(mod.module);
  for (const d of mod.declarations) {
    fullKnown.set(d.name, mod.module);
    for (const [m, n] of d.refs) if (!fullKnown.has(n)) fullKnown.set(n, m);
  }
}
for (const m of fullKnown.values()) fullKnownModules.add(m);
{
  const text = await Deno.readTextFile(linkIndexPath);
  let module = "";
  let pos = 0;
  const n = text.length;
  while (pos < n) {
    let nl = text.indexOf("\n", pos);
    if (nl < 0) nl = n;
    const c = text.charCodeAt(pos);
    if (c === 9) fullLinkIndex.set(text.slice(pos + 1, nl), module);
    else if (c === 64) fullKnownModules.add(text.slice(pos + 1, nl));
    else if (c === 35) { /* format marker */ }
    else if (nl > pos) module = text.slice(pos, nl);
    pos = nl + 1;
  }
}

// ------------------------------------------------------------- agreement zone

/**
 * Whether a name may go into a world at all.
 *
 * Everything rejected here is a place the two specifications are known to
 * differ, so putting it in would produce a difference that says nothing.
 */
function admissible(name: string): boolean {
  if (!prototype.isNameLit(name)) return false;
  if (name.includes("«") || name.includes("»")) return false;
  if (name.startsWith("_private.")) return false;
  const last = name.slice(name.lastIndexOf(".") + 1);
  return !AUTO_SUFFIXES.has(last);
}

/** Words a docstring could plausibly look up, over-approximated from its text. */
function tokensOf(md: string): Set<string> {
  const out = new Set<string>();
  for (const raw of md.split(/[\p{Z}\p{C}]/u)) {
    const trimmed = raw.replace(/^[`*_[\](){}<>"'.,;:!?]+/, "").replace(
      /[`*_[\](){}<>"',;:]+$/,
      "",
    );
    for (const piece of [raw, trimmed]) {
      if (piece === "") continue;
      out.add(piece);
      const dot = piece.lastIndexOf(".");
      if (dot >= 0) out.add(piece.slice(dot + 1));
    }
  }
  return out;
}

type World = { modules: string[]; names: Record<string, string> };

/** The part of the real maps a docstring can reach, inside the agreement zone. */
function worldFor(md: string): World {
  const names: Record<string, string> = {};
  const modules = new Set<string>();
  for (const token of [...tokensOf(md)].sort()) {
    if (!admissible(token)) continue;
    const owner = fullKnown.get(token) ?? fullLinkIndex.get(token);
    if (owner !== undefined && admissible(owner)) {
      names[token] = owner;
      modules.add(owner);
    }
    if (fullKnownModules.has(token)) modules.add(token);
  }
  return { modules: [...modules].sort(), names };
}

// -------------------------------------------------------------------- corpus

type Case = { what: string; depth: number; md: string; world: World };

/**
 * Hand-written cases, with hand-written worlds.
 *
 * These are the ones that make the referee worth running: the shapes that
 * separate the two specifications, and the identifier characters the package
 * happens not to use in a resolvable position.
 */
const CURATED: { what: string; depth: number; md: string; world: World }[] = [
  {
    what: "curated: a code span inside a link is not auto-linked",
    depth: 1,
    md: "[`Pkg.A.f`](x) and `Pkg.A.f`\n",
    world: { modules: ["Pkg.A"], names: { "Pkg.A.f": "Pkg.A" } },
  },
  {
    what: "curated: a code span inside an emphasised link is not auto-linked",
    depth: 1,
    md: "[*`Pkg.A.f`*](x)\n",
    world: { modules: ["Pkg.A"], names: { "Pkg.A.f": "Pkg.A" } },
  },
  {
    what: "curated: emphasis outside a link still auto-links",
    depth: 1,
    md: "*`Pkg.A.f`*\n",
    world: { modules: ["Pkg.A"], names: { "Pkg.A.f": "Pkg.A" } },
  },
  {
    what: "curated: a declaration, a module and an unknown word",
    depth: 1,
    md: "`Pkg.A.f Pkg.A Unknown.g`\n",
    world: { modules: ["Pkg.A"], names: { "Pkg.A.f": "Pkg.A" } },
  },
  {
    what: "curated: the tail after the last dot",
    depth: 1,
    md: "`Nat.succ Foo.Nat.succ`\n",
    world: { modules: ["Pkg.A"], names: { "succ": "Pkg.A" } },
  },
  {
    what: "curated: apostrophe, bang and question mark in a resolvable name",
    depth: 0,
    md: "`Pkg.A.f' Pkg.A.g! Pkg.A.h?`\n",
    world: {
      modules: ["Pkg.A"],
      names: { "Pkg.A.f'": "Pkg.A", "Pkg.A.g!": "Pkg.A", "Pkg.A.h?": "Pkg.A" },
    },
  },
  {
    what: "curated: letter-like above the BMP in a resolvable name",
    depth: 0,
    md: "`\u{1d49c} Pkg.A.\u{1d59f}'`\n",
    world: {
      modules: ["Pkg.A"],
      names: { "\u{1d49c}": "Pkg.A", "Pkg.A.\u{1d59f}'": "Pkg.A" },
    },
  },
  {
    what: "curated: greek and letter-like names",
    depth: 0,
    md: "`α Ω ℕ x₁`\n",
    world: {
      modules: ["Pkg.A"],
      names: { "α": "Pkg.A", "Ω": "Pkg.A", "ℕ": "Pkg.A", "x₁": "Pkg.A" },
    },
  },
  {
    what: "curated: λ, Π and Σ are not letter-like",
    depth: 0,
    md: "`λ Π Σ`\n",
    world: { modules: ["Pkg.A"], names: {} },
  },
  {
    what: "curated: a numeric component",
    depth: 0,
    md: "`Pkg.A.1`\n",
    world: { modules: ["Pkg.A"], names: { "Pkg.A.1": "Pkg.A" } },
  },
  {
    what: "curated: consecutive separators",
    depth: 0,
    md: "`  Pkg.A.f \t `\n",
    world: { modules: ["Pkg.A"], names: { "Pkg.A.f": "Pkg.A" } },
  },
  {
    what: "curated: a source path needs no map",
    depth: 2,
    md: "`Foo/Bar.lean Foo.lean`\n",
    world: { modules: [], names: {} },
  },
  {
    what: "curated: a name search that resolves, one that does not",
    depth: 1,
    md: "[a](##Pkg.A.f) [b](##Pkg.A.gone) [c](##Pkg.A)\n",
    world: { modules: ["Pkg.A"], names: { "Pkg.A.f": "Pkg.A" } },
  },
  {
    what: "curated: a lean code block is auto-linked and python is not",
    depth: 1,
    md: "```lean\nPkg.A.f\n```\n\n```\nPkg.A.f\n```\n\n```python\nPkg.A.f\n```\n",
    world: { modules: ["Pkg.A"], names: { "Pkg.A.f": "Pkg.A" } },
  },
  {
    what: "curated: a module with one component",
    depth: 0,
    md: "`Pkg Pkg.f`\n",
    world: { modules: ["Pkg"], names: { "Pkg.f": "Pkg" } },
  },
  {
    what: "curated: a name that is also a module",
    depth: 1,
    md: "`Pkg.Both`\n",
    world: { modules: ["Pkg.Both", "Pkg.Owner"], names: { "Pkg.Both": "Pkg.Owner" } },
  },
  {
    what: "curated: several anchors in one span, with text between",
    depth: 2,
    md: "`Pkg.A.f (Pkg.A.g) Pkg.A.h`\n",
    world: {
      modules: ["Pkg.A"],
      names: { "Pkg.A.f": "Pkg.A", "Pkg.A.g": "Pkg.A", "Pkg.A.h": "Pkg.A" },
    },
  },
  {
    what: "curated: a heading containing a resolvable name",
    depth: 1,
    md: "# About `Pkg.A.f`\n",
    world: { modules: ["Pkg.A"], names: { "Pkg.A.f": "Pkg.A" } },
  },
  {
    what: "curated: a list and a quote containing resolvable names",
    depth: 1,
    md: "- `Pkg.A.f`\n- x\n\n> `Pkg.A.g`\n",
    world: {
      modules: ["Pkg.A"],
      names: { "Pkg.A.f": "Pkg.A", "Pkg.A.g": "Pkg.A" },
    },
  },
];

/** Real docstrings, chosen for how much of the map they reach. */
const seen = new Set<string>();
const realAll: { what: string; depth: number; md: string; module: string }[] = [];
for (const mod of irModules) {
  const depth = (mod.module as string).split(".").length - 1;
  const add = (what: string, md: unknown) => {
    if (typeof md !== "string" || seen.has(md)) return;
    seen.add(md);
    realAll.push({ what, depth, md, module: mod.module });
  };
  for (const [i, doc] of mod.moduleDocs.entries()) add(`${mod.module} module doc ${i}`, doc.text);
  for (const decl of mod.declarations) {
    add(`${decl.name}`, decl.doc);
    for (const member of decl.members ?? []) add(`${decl.name}.${member.name}`, member.doc);
  }
}

/** `getRoot`: what `depthToRoot` produces. */
const rootOf = (depth: number) => "../".repeat(depth) + "./";

/**
 * The prototype's answer in a given world. Used twice: to pick the cases that
 * resolve something (so that the corpus is not mostly inert text), and, after
 * the oracle has run, to record where the prototype and doc-gen4 part company.
 *
 * `moduleDeclNames` is empty because doc-gen4's matching branch is disabled
 * here (`currentName := none`); anything else would compare two different
 * things.
 */
function renderPrototype(c: { depth: number; md: string; world: World }): string {
  prototype.known.clear();
  prototype.linkIndex.clear();
  for (const [n, m] of Object.entries(c.world.names)) prototype.known.set(n, m);
  return prototype.renderDocString(c.md, {
    root: rootOf(c.depth),
    moduleDeclNames: [],
    knownModules: new Set(c.world.modules),
  });
}

const countAnchors = (html: string) => (html.match(/<a href="/g) ?? []).length;

const scored = realAll
  .filter((c) => c.md.length <= COMPACT_CHARS)
  .map((c) => ({ ...c, world: worldFor(c.md) }))
  .map((c) => ({ ...c, anchors: countAnchors(renderPrototype(c)) }))
  .filter((c) => c.anchors > 0)
  .sort((a, b) => b.anchors - a.anchors);

// A spread over the ranking rather than the top of it, so the sample is not all
// one shape of docstring.
const picked: typeof scored = [];
const stride = Math.max(1, Math.floor(scored.length / REAL_CASES));
for (let i = 0; i < scored.length && picked.length < REAL_CASES; i += stride) picked.push(scored[i]);

const cases: Case[] = [
  ...CURATED,
  ...picked.map((c) => ({ what: c.what, depth: c.depth, md: c.md, world: c.world })),
];
console.error(`${CURATED.length} curated + ${picked.length} real cases`);

// -------------------------------------------------------------------- oracle

const DYLIB = Deno.build.os === "darwin" ? "dylib" : "so";
const LIBS = [
  `.lake/packages/MD4Lean/.lake/build/lib/libleanmd4c.${DYLIB}`,
  `.lake/packages/MD4Lean/.lake/build/lib/libMD4Lean_MD4Lean.${DYLIB}`,
  `.lake/packages/UnicodeBasic/.lake/build/lib/libUnicodeBasic_UnicodeBasic.${DYLIB}`,
];

const work = await Deno.makeTempDir({ prefix: "docgen4-linked-" });
const inPath = `${work}/corpus.jsonl`;
const outPath = `${work}/html.jsonl`;
await Deno.writeTextFile(
  inPath,
  cases
    .map((c) =>
      JSON.stringify([
        c.depth,
        c.md,
        c.world.modules,
        Object.entries(c.world.names).map(([n, m]) => [n, c.world.modules.indexOf(m)]),
      ])
    )
    .join("\n") + "\n",
);

const { code, signal } = await new Deno.Command("lake", {
  args: ["env", "lean", ...LIBS.map((l) => `--load-dynlib=${l}`), "--run", DUMPER.pathname, inPath, outPath],
  cwd: target,
  stdout: "inherit",
  stderr: "inherit",
}).output();
if (code !== 0) {
  console.error(`the dumper failed (${signal ?? code})`);
  Deno.exit(4);
}
const answers: string[] = (await Deno.readTextFile(outPath))
  .split("\n")
  .filter((l) => l !== "")
  .map((l) => JSON.parse(l));
if (answers.length !== cases.length) {
  console.error(`${answers.length} answers for ${cases.length} cases`);
  Deno.exit(4);
}
await Deno.remove(work, { recursive: true });

// ------------------------------------------------- the prototype, same worlds

const prototypeDiffers: string[] = [];
for (const [i, c] of cases.entries()) {
  if (renderPrototype(c) !== answers[i]) prototypeDiffers.push(c.what);
}
console.error(
  `the prototype differs from doc-gen4 on ${prototypeDiffers.length} of ${cases.length} cases`,
);
for (const what of prototypeDiffers) console.error(`  ${what}`);

// --------------------------------------------------------------------- output

const manifest = await readJson(`${target}/lake-manifest.json`);
// deno-lint-ignore no-explicit-any
const docGen4 = (manifest.packages ?? []).find((p: any) =>
  p.name === "doc-gen4" || p.name === "«doc-gen4»"
);
const oracleFiles = ["DocGen4/Output/DocString.lean", "DocGen4/Output/ToHtmlFormat.lean"];
const dirty = await new Deno.Command("git", {
  args: ["diff", "--quiet", "--", ...oracleFiles],
  cwd: `${target}/.lake/packages/doc-gen4`,
  stdout: "null",
  stderr: "null",
}).output();
if (dirty.code !== 0) {
  console.error(`${oracleFiles.join(" and ")} have local changes; the oracle is not doc-gen4`);
  Deno.exit(5);
}

const fixture = JSON.stringify({
  generatedBy: "crates/lean-doc-render/tests/oracle/gen-docgen4-linked-expected.ts",
  oracle: "DocGen4.Output.docStringToHtml with a populated AnalyzerResult, run under lake env " +
    "lean in the measurement target",
  agreementZone: "no private names, no auto-generated eliminator suffixes, no guillemet " +
    "components, and currentName := none so the module-local branch never fires",
  target,
  leanToolchain: (await Deno.readTextFile(`${target}/lean-toolchain`)).trim(),
  docGen4Rev: docGen4?.rev ?? null,
  docGen4OracleFilesClean: oracleFiles,
  ir,
  linkIndexPath,
  renderTsRanges: RANGES,
  prototypeDiffers,
  deno: Deno.version.deno,
  cases: cases.map((c, i) => ({
    what: c.what,
    root: rootOf(c.depth),
    modules: c.world.modules,
    names: c.world.names,
    md: c.md,
    html: answers[i],
  })),
}) + "\n";

if (check) {
  const committed = await Deno.readTextFile(FIXTURE);
  if (committed !== fixture) {
    console.error(`${FIXTURE.pathname} is not what this script produces`);
    Deno.exit(1);
  }
  console.error(`${FIXTURE.pathname} is current (${cases.length} cases)`);
} else {
  await Deno.writeTextFile(FIXTURE, fixture);
  console.error(
    `${cases.length} cases -> ${FIXTURE.pathname} ` +
      `(${new TextEncoder().encode(fixture).length} B)`,
  );
}
