[package]
name = "lean-doc"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
lean-doc-global = { path = "../lean-doc-global" }
lean-doc-incr = { path = "../lean-doc-incr" }
lean-doc-ir = { path = "../lean-doc-ir" }
lean-doc-render = { path = "../lean-doc-render" }
serde_json = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
