//! The `merge` stage: folding a partial extraction back into the package IR.
//!
//! Ported from `experiments/stage5/merge-ir.ts` (frozen). Milestone **M3-b**.
//!
//! The extractor writes a *complete* IR tree for whatever module list it was
//! given, so a one-module run produces a one-module tree. Two things therefore
//! have to be repaired before that tree is usable as an update:
//!
//! 1. `index.json` must keep the other 431 modules' entries. The entry for the
//!    re-extracted module is taken verbatim from the partial run — including its
//!    `contentHash`, which only Lean can compute (it is `String.hash` of the
//!    module JSON).
//!
//! 2. `deps/*.json` is **package-global and cannot be produced by a partial run
//!    at all.** The extractor decides "dependency" as "defining module not in
//!    the target list", so with a one-module target list the package's own other
//!    modules are misfiled as dependencies. The fix is not to merge that file
//!    but to recompute the slice from the merged module files, which is where
//!    the `refs` live anyway.
//!
//! This is the first place where "one module changed" stops being local, and it
//! is worth being precise about why: it is not a dependency of the *change*, it
//! is an artefact of the extractor's interface.
//!
//! # The one place this port is deliberately not the prototype
//!
//! `merge-ir.ts:222-227` writes each `deps/<Root>.json` in **insertion order**;
//! the from-scratch writer (`Extract.lean:2052-2057`, via Lean's `Json.mkObj`,
//! which is backed by a sorted map) writes it **sorted** — top-level keys
//! `declarations` / `package` / `schemaVersion`, and the declaration names in
//! code point order. Plan §7 recorded that as the one place the incremental IR
//! was already not byte-identical to a full extraction, and left the choice to
//! M3. **This port writes Lean's order**, so that
//!
//! > every file an incremental build produces is byte for byte the one a
//! > from-scratch extraction would have written
//!
//! is an invariant a test can hold (`tests/merge.rs`). It is measured, not
//! assumed: the fixture is the real from-scratch tree. On the target, a merged
//! tree over a re-extraction that changed nothing **is** the from-scratch tree,
//! byte for byte, `index.json` and all 26 dependency slices included
//! 【実測 2026-08-12】.
//!
//! **The change does not reach the site**【実測 2026-08-12】. Two IR trees whose
//! only difference is these three files' key order were rendered and had their
//! six whole-package artifacts derived: **438 of 438 files byte-identical,
//! 31,617,612 B**. That is not luck — `render.ts` reads the `.lidx`, not
//! `deps/`, and `global.ts:319` re-sorts the dependency names it reads
//! (`Object.keys(deps).sort()`) — but a claim about generated bytes is worth a
//! measurement rather than a reading.
//!
//! Lean's order is **code point order** ([`str::cmp`]), not the UTF-16 order of
//! plan §7's U1 — Lean compares `String`s by their characters. The two agree
//! throughout the BMP and part company at U+10000, so the choice is only visible
//! on a name containing a supplementary scalar; `tests/merge.rs` builds one
//! rather than waiting for Mathlib to.
//!
//! The divergence is **the whole of what it takes to make a merged tree a
//! from-scratch one**, so `index.json` is written Lean's way too:
//!
//! - each `dependencyMaps` entry's keys are `bytes` / `entries` / `file` /
//!   `package` — `Json.mkObj`'s alphabetical order, not the prototype's object
//!   literal. Without this the merged index is the same 88,541 B and the same
//!   data as the from-scratch one and still not the same bytes【実測 2026-08-12】.
//! - the `dependencyMaps` **array** is in code point order, following
//!   `Extract.lean:2050` (`a.1.toString < b.1.toString`) rather than the
//!   prototype's UTF-16 `.sort()`.
//!
//! So **nothing this module writes is ordered the prototype's way** — every
//! order in a merged tree is the one Lean would have produced. `index.json`'s
//! top-level key order is the base index's, which the prototype gets from a
//! spread and Lean from `Json.mkObj`; the two agree, so nothing had to be
//! chosen. Reproduced explicitly by [`JsonObject`] rather than by trusting a map
//! type (plan §7).

use std::collections::{BTreeMap, HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::time::Instant;

use lean_doc_ir::read_module_file;
use serde::de::{MapAccess, Visitor};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use serde_json::Value;

use crate::detect::{Error, write, write_json_line, write_text};

/// What `merge` needs to know.
#[derive(Clone, Copy, Debug)]
pub struct MergeOptions<'a> {
    /// The IR to update. **Never modified in place unless `out` says so.**
    pub base: &'a Path,
    /// The partial extraction's tree. `None` is a real case, not a misuse: a
    /// pure deletion re-extracts nothing.
    pub inc: Option<&'a Path>,
    /// Where the merged tree goes. The prototype defaults it to `base +
    /// ".merged"`; here the caller says so, and the pipeline passes `base`.
    pub out: &'a Path,
    /// Modules that no longer exist. They leave the index and their module files
    /// are deleted, which is the IR third of the deletion path (the other two
    /// are the pages and the ledger).
    pub removed: &'a [String],
    /// The modules whose IR `contentHash` moved, one per line — the render set's
    /// input, and **not** the same as the re-extracted set.
    pub changed_out: Option<&'a Path>,
    pub timings: Option<&'a Path>,
}

/// What `merge` did.
///
/// **No `PartialEq`**: the three `*Seconds` are wall clock, and a summary that
/// compares equal to another one would be asserting on them.
#[derive(Clone, Debug)]
pub struct MergeSummary {
    /// Every module the partial extraction carried, in its index order.
    pub updated: Vec<String>,
    /// How many of `removed` were actually in the base index.
    pub removed: usize,
    /// The **output**-side hash moved for these: `contentHash` is `String.hash`
    /// of the module JSON, computed by the extractor. A re-extracted module
    /// whose hash did not move produces the same page, so it does not enter the
    /// render set. This is the second ledger, and it is the one that decides
    /// what to re-render.
    pub ir_changed: Vec<String>,
    /// Modules in the merged index.
    pub modules: usize,
    /// Declarations across them.
    pub declarations: usize,
    /// One per `deps/<Root>.json` written, in the order they were written.
    pub dep_maps: Vec<DepMapRecord>,
    pub copy_seconds: f64,
    pub deps_seconds: f64,
    pub total_seconds: f64,
}

/// One `dependencyMaps` entry of the merged `index.json`.
///
/// Field order **is** the file's key order, and it is **Lean's alphabetical
/// one**, not the prototype's object literal — see the module heading.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct DepMapRecord {
    /// The slice's UTF-8 byte count. Key order does not change it — the keys and
    /// values are the same bytes in a different sequence — which is what
    /// `tools/merge-compare.sh` checks rather than assumes.
    pub bytes: usize,
    pub entries: usize,
    pub file: String,
    pub package: String,
}

/// One `deps/<Root>.json`, in the order **Lean** writes it.
///
/// `declarations` is a [`BTreeMap`], whose iteration order is `str`'s `Ord` =
/// code point order = Lean's `String` comparison. That is the whole of the
/// deliberate divergence from the prototype.
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct DepSlice<'a> {
    declarations: &'a BTreeMap<String, String>,
    package: &'a str,
    /// Carried through from the base index rather than assumed to be 4, and
    /// **omitted when the base index has none** — that is what `JSON.stringify`
    /// does with an `undefined` property.
    #[serde(skip_serializing_if = "Option::is_none")]
    schema_version: Option<&'a Value>,
}

/// A JSON object that remembers the order its keys arrived in.
///
/// The merged `index.json` is the base index with four values replaced, so its
/// key order is the base file's. `serde_json`'s own map would do this too *with
/// the `preserve_order` feature on*, and that is exactly why this type exists:
/// plan §7 says to reproduce the order explicitly rather than to inherit it from
/// a dependency's build configuration. Same shape as
/// [`crate::ledger::KeySet`], for the same reason.
///
/// The **values** are `serde_json::Value`s copied verbatim out of the base and
/// incremental indexes, and their nested key order does rely on
/// `preserve_order`; `tests/merge.rs` asserts a round trip rather than trusting
/// it.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct JsonObject(Vec<(String, Value)>);

impl JsonObject {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds a key, or replaces the value of one already present **in place** —
    /// which is what a JavaScript spread followed by a property assignment does,
    /// and what makes the merged index keep the base index's key order.
    pub fn insert(&mut self, key: impl Into<String>, value: Value) {
        let key = key.into();
        match self.0.iter_mut().find(|(name, _)| *name == key) {
            Some(slot) => slot.1 = value,
            None => self.0.push((key, value)),
        }
    }

    #[must_use]
    pub fn get(&self, key: &str) -> Option<&Value> {
        self.0
            .iter()
            .find(|(name, _)| name == key)
            .map(|(_, value)| value)
    }

    pub fn keys(&self) -> impl Iterator<Item = &str> {
        self.0.iter().map(|(name, _)| name.as_str())
    }

    fn iter(&self) -> impl Iterator<Item = (&str, &Value)> {
        self.0.iter().map(|(name, value)| (name.as_str(), value))
    }
}

impl Serialize for JsonObject {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.collect_map(self.iter())
    }
}

impl<'de> Deserialize<'de> for JsonObject {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct JsonObjectVisitor;
        impl<'de> Visitor<'de> for JsonObjectVisitor {
            type Value = JsonObject;

            fn expecting(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str("a JSON object")
            }

            fn visit_map<M: MapAccess<'de>>(self, mut map: M) -> Result<JsonObject, M::Error> {
                let mut object = JsonObject::new();
                while let Some((key, value)) = map.next_entry::<String, Value>()? {
                    object.insert(key, value);
                }
                Ok(object)
            }
        }
        deserializer.deserialize_map(JsonObjectVisitor)
    }
}

/// Folds `inc` into `base` and writes the result to `out`.
pub fn merge(options: &MergeOptions<'_>) -> Result<MergeSummary, Error> {
    let started = Instant::now();
    let base_index_path = options.base.join("index.json");
    let base_index: JsonObject = read_json(&base_index_path)?;
    // A pure deletion re-extracts nothing, so there may be no incremental tree
    // at all. That is a real case, not a misuse.
    let inc_modules: Vec<IndexEntry> = match options.inc {
        Some(dir) => {
            let path = dir.join("index.json");
            let index: JsonObject = read_json(&path)?;
            index_entries(&index, &path)?
        }
        None => Vec::new(),
    };
    let base_modules = index_entries(&base_index, &base_index_path)?;

    let mut entries: HashMap<String, IndexEntry> = HashMap::new();
    let mut order: Vec<String> = Vec::with_capacity(base_modules.len());
    for entry in &base_modules {
        order.push(entry.module.clone());
        entries.insert(entry.module.clone(), entry.clone());
    }

    // Deletion, the IR half. A module that no longer exists has to leave the
    // index, or it keeps a page and keeps feeding names to the dependency slice
    // and the global maps. The other two halves are the caller's: the pages
    // (`prune`) and the ledger (rebuilt, which costs the same as checking it —
    // so there is no incremental ledger-update path to write).
    let mut gone: Vec<String> = Vec::new();
    let mut dropped_files: Vec<String> = Vec::new();
    let mut gone_set: HashSet<String> = HashSet::new();
    for module in options.removed {
        if let Some(entry) = entries.get(module)
            && gone_set.insert(module.clone())
        {
            dropped_files.push(entry.file.clone());
            gone.push(module.clone());
        }
    }
    for module in &gone {
        entries.remove(module);
    }
    order.retain(|module| !gone_set.contains(module));

    fs::create_dir_all(options.out.join("modules")).map_err(|source| Error::Io {
        path: options.out.join("modules"),
        source,
    })?;
    fs::create_dir_all(options.out.join("deps")).map_err(|source| Error::Io {
        path: options.out.join("deps"),
        source,
    })?;

    let in_inc: HashSet<&str> = inc_modules
        .iter()
        .map(|entry| entry.module.as_str())
        .collect();
    if options.out != options.base {
        // Copy the untouched part. This is the cost of not updating in place; a
        // real driver keeps one directory and rewrites only the changed files.
        for entry in &base_modules {
            if gone_set.contains(&entry.module) || in_inc.contains(entry.module.as_str()) {
                continue;
            }
            copy(
                &options.base.join(&entry.file),
                &options.out.join(&entry.file),
            )?;
        }
    } else {
        for file in &dropped_files {
            // `Deno.remove(...).catch(() => {})`: a module file that is already
            // gone is the state this line is trying to reach.
            let _ = fs::remove_file(options.out.join(file));
        }
    }

    let mut updated: Vec<String> = Vec::with_capacity(inc_modules.len());
    let mut ir_changed: Vec<String> = Vec::new();
    for entry in &inc_modules {
        let inc = options
            .inc
            .expect("there are entries only when there is a tree");
        copy(&inc.join(&entry.file), &options.out.join(&entry.file))?;
        let before = entries.get(&entry.module);
        if before.is_none() {
            order.push(entry.module.clone());
        }
        if before.is_none_or(|was| was.raw.get("contentHash") != entry.raw.get("contentHash")) {
            ir_changed.push(entry.module.clone());
        }
        entries.insert(entry.module.clone(), entry.clone());
        updated.push(entry.module.clone());
    }
    let modules_done = started.elapsed();

    // Recompute the dependency slice from the merged module files: a reference
    // is a dependency iff its defining module is not one of the package's.
    let own: HashSet<&str> = order.iter().map(String::as_str).collect();
    let mut dep: BTreeMap<String, String> = BTreeMap::new();
    let mut declarations = 0usize;
    for module in &order {
        let entry = &entries[module];
        let parsed = read_module_file(&options.out.join(&entry.file)).map_err(Error::Ir)?;
        declarations += parsed.declarations.len();
        for decl in &parsed.declarations {
            for reference in &decl.refs {
                if !own.contains(reference.module.as_str()) {
                    // Last writer wins, as `Map.prototype.set` does.
                    dep.insert(reference.name.clone(), reference.module.clone());
                }
            }
        }
    }

    let mut by_root: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    for (name, module) in &dep {
        by_root
            .entry(module_root(module).to_owned())
            .or_default()
            .insert(name.clone(), module.clone());
    }
    // The **roots** follow Lean too, not the prototype: they are the order of
    // `index.json`'s `dependencyMaps` array, and that file is one of the two this
    // milestone writes the from-scratch way. `Extract.lean:2050` sorts them with
    // `a.1.toString < b.1.toString` = Lean's `String` comparison = code point
    // order = `str`'s `Ord`, where the prototype's `.sort()` is UTF-16 (plan §7
    // U1). Every root on the target is ASCII, where the two agree;
    // `tests/merge.rs` builds a pair that does not and pins this side.
    let mut roots: Vec<&String> = by_root.keys().collect();
    roots.sort();

    let schema_version = base_index.get("schemaVersion");
    let mut dep_maps: Vec<DepMapRecord> = Vec::with_capacity(roots.len());
    for root in roots {
        let declarations = &by_root[root];
        let body = serde_json::to_string(&DepSlice {
            declarations,
            package: root,
            schema_version,
        })
        .expect("a dependency slice is strings and one number");
        let file = format!("deps/{root}.json");
        write(&options.out.join(&file), &body)?;
        dep_maps.push(DepMapRecord {
            package: root.clone(),
            file,
            entries: declarations.len(),
            bytes: body.len(),
        });
    }

    // Drop dependency files that no longer belong (a package that stopped being
    // referenced, or the own-package slice a partial run wrongly produced).
    let kept: HashSet<&str> = dep_maps.iter().map(|record| record.file.as_str()).collect();
    let deps_dir = options.out.join("deps");
    let listing = fs::read_dir(&deps_dir).map_err(|source| Error::Io {
        path: deps_dir.clone(),
        source,
    })?;
    let mut stale: Vec<PathBuf> = Vec::new();
    for found in listing {
        let found = found.map_err(|source| Error::Io {
            path: deps_dir.clone(),
            source,
        })?;
        let name = found.file_name();
        let relative = format!("deps/{}", name.to_string_lossy());
        if !kept.contains(relative.as_str()) {
            stale.push(deps_dir.join(name));
        }
    }
    // Sorted so that a failure names the same file whatever the directory
    // listing's order was; the removal itself does not care.
    stale.sort();
    for path in stale {
        fs::remove_file(&path).map_err(|source| Error::Io { path, source })?;
    }

    let mut index = base_index.clone();
    index.insert("moduleCount", Value::from(order.len()));
    index.insert("declarationCount", Value::from(declarations));
    index.insert(
        "modules",
        Value::Array(order.iter().map(|m| entries[m].raw.clone()).collect()),
    );
    index.insert(
        "dependencyMaps",
        serde_json::to_value(&dep_maps).expect("counts and strings serialise"),
    );
    write(
        &options.out.join("index.json"),
        &serde_json::to_string(&index).expect("the index came from JSON"),
    )?;
    let total = started.elapsed();

    let summary = MergeSummary {
        updated,
        removed: gone.len(),
        ir_changed,
        modules: order.len(),
        declarations,
        dep_maps,
        copy_seconds: modules_done.as_secs_f64(),
        deps_seconds: (total - modules_done).as_secs_f64(),
        total_seconds: total.as_secs_f64(),
    };
    if let Some(path) = options.changed_out {
        write_text(path, &summary.ir_changed)?;
    }
    if let Some(path) = options.timings {
        write_json_line(
            path,
            &MergeTimings {
                command: "merge",
                updated: summary.updated.len(),
                removed: summary.removed,
                ir_changed: summary.ir_changed.len(),
                modules: summary.modules,
                copy_seconds: summary.copy_seconds,
                deps_seconds: summary.deps_seconds,
                total_seconds: summary.total_seconds,
            },
        )?;
    }
    Ok(summary)
}

/// The `--timings` record. Key order is the prototype's object literal
/// (`merge-ir.ts:272-281`); the three `*Seconds` are **diagnostics**.
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct MergeTimings<'a> {
    command: &'a str,
    updated: usize,
    removed: usize,
    ir_changed: usize,
    modules: usize,
    copy_seconds: f64,
    deps_seconds: f64,
    total_seconds: f64,
}

/// First component of a module name — the extractor's `moduleRoot`.
///
/// `"".split(".")[0]` is `""` in JavaScript and `""` here: a root nobody can
/// name, which is what a reference to a module with an empty name would produce.
fn module_root(module: &str) -> &str {
    module.split('.').next().unwrap_or("")
}

// ---------------------------------------------------------------- verify

/// The result of `merge --verify A --against B`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct VerifyReport {
    /// Everything the prototype prints, in order, one line per entry.
    pub lines: Vec<String>,
    /// Problems found. Zero is exit 0.
    pub problems: usize,
    /// Module files that were byte for byte the same.
    pub module_files_identical: usize,
    pub modules_in_a: usize,
    pub dependency_entries_in_a: usize,
    pub dependency_entries_in_b: usize,
    pub dependency_mismatches: usize,
}

impl VerifyReport {
    /// The text `merge --verify` prints, which is the whole of its answer.
    #[must_use]
    pub fn to_text(&self) -> String {
        self.lines
            .iter()
            .map(|line| format!("{line}\n"))
            .collect::<String>()
    }
}

/// Compares two IR trees: module files byte for byte, index entries field by
/// field, dependency slices **as name -> module maps**.
///
/// The last of those is the prototype's own note, and it is now weaker than it
/// has to be: it says the slices' key order "comes out of a Lean HashMap and is
/// not reproducible outside Lean". It is (see the module heading), and
/// `tests/merge.rs` compares those files byte for byte. This comparison is left
/// on the mapping anyway, because it is what tells a *pipeline* that two trees
/// mean the same thing — and it is the only check that survives a future
/// extractor that emits them in another order.
pub fn verify(a: &Path, b: &Path) -> Result<VerifyReport, Error> {
    let mut lines: Vec<String> = Vec::new();
    let a_index_path = a.join("index.json");
    let b_index_path = b.join("index.json");
    let index_a: JsonObject = read_json(&a_index_path)?;
    let index_b: JsonObject = read_json(&b_index_path)?;
    let mut problems = 0usize;

    let map_a = module_map(&index_a, &a_index_path)?;
    let map_b = module_map(&index_b, &b_index_path)?;
    if map_a.len() != map_b.len() {
        lines.push(format!(
            "FAIL module count {} vs {}",
            map_a.len(),
            map_b.len()
        ));
        problems += 1;
    }
    let mut same = 0usize;
    for (name, entry_a) in &map_a {
        let Some(entry_b) = map_b
            .iter()
            .find(|(other, _)| other == name)
            .map(|(_, e)| e)
        else {
            lines.push(format!("FAIL missing in B: {name}"));
            problems += 1;
            continue;
        };
        for key in ["file", "bytes", "declarations", "contentHash"] {
            if entry_a.raw.get(key) != entry_b.raw.get(key) {
                lines.push(format!(
                    "FAIL index.{key} {name}: {} vs {}",
                    js_display(entry_a.raw.get(key)),
                    js_display(entry_b.raw.get(key)),
                ));
                problems += 1;
            }
        }
        let bytes_a = read(&a.join(&entry_a.file))?;
        let bytes_b = read(&b.join(&entry_b.file))?;
        if bytes_a == bytes_b {
            same += 1;
        } else {
            lines.push(format!("FAIL bytes differ: {name}"));
            problems += 1;
        }
    }
    lines.push(format!(
        "module files byte-identical: {same}/{}",
        map_a.len()
    ));

    // Dependency slices, compared as mappings.
    let dep_a = dep_mapping(a, &index_a, &a_index_path)?;
    let dep_b = dep_mapping(b, &index_b, &b_index_path)?;
    let lookup_b: HashMap<&str, &str> = dep_b
        .iter()
        .map(|(name, module)| (name.as_str(), module.as_str()))
        .collect();
    let lookup_a: HashSet<&str> = dep_a.iter().map(|(name, _)| name.as_str()).collect();
    let mut dep_bad = 0usize;
    for (name, module) in &dep_a {
        if lookup_b.get(name.as_str()).copied() != Some(module.as_str()) {
            if dep_bad < VERIFY_DEP_FAILURES {
                lines.push(format!(
                    "FAIL dep {name}: {module} vs {}",
                    lookup_b
                        .get(name.as_str())
                        .map_or("undefined", |found| *found)
                ));
            }
            dep_bad += 1;
        }
    }
    for (name, _) in &dep_b {
        if !lookup_a.contains(name.as_str()) {
            if dep_bad < VERIFY_DEP_FAILURES {
                lines.push(format!("FAIL dep only in B: {name}"));
            }
            dep_bad += 1;
        }
    }
    lines.push(format!(
        "dependency map entries: {} vs {}, mismatches {dep_bad}",
        dep_a.len(),
        dep_b.len()
    ));
    problems += dep_bad;
    lines.push(if problems == 0 {
        "VERIFY OK".to_owned()
    } else {
        format!("VERIFY FAILED ({problems} problems)")
    });

    Ok(VerifyReport {
        lines,
        problems,
        module_files_identical: same,
        modules_in_a: map_a.len(),
        dependency_entries_in_a: dep_a.len(),
        dependency_entries_in_b: dep_b.len(),
        dependency_mismatches: dep_bad,
    })
}

/// How many differing dependency names `verify` names before it only counts.
const VERIFY_DEP_FAILURES: usize = 10;

/// `new Map(index.modules.map(e => [e.module, e]))`: a repeated module keeps its
/// first position and takes its last value.
fn module_map(index: &JsonObject, path: &Path) -> Result<Vec<(String, IndexEntry)>, Error> {
    let mut out: Vec<(String, IndexEntry)> = Vec::new();
    for entry in index_entries(index, path)? {
        match out.iter_mut().find(|(name, _)| *name == entry.module) {
            Some(slot) => slot.1 = entry,
            None => out.push((entry.module.clone(), entry)),
        }
    }
    Ok(out)
}

/// Every dependency slice of a tree, flattened to `name -> module` in file
/// order — `idx.dependencyMaps ?? []`, so a tree with no such key is empty
/// rather than a failure.
fn dep_mapping(
    root: &Path,
    index: &JsonObject,
    path: &Path,
) -> Result<Vec<(String, String)>, Error> {
    let mut out: Vec<(String, String)> = Vec::new();
    let entries = match index.get("dependencyMaps") {
        None | Some(Value::Null) => Vec::new(),
        Some(Value::Array(entries)) => entries.clone(),
        Some(_) => {
            return Err(Error::IndexShape {
                path: path.to_owned(),
                message: "dependencyMaps is not an array".to_owned(),
            });
        }
    };
    for entry in entries {
        let Some(Value::String(file)) = entry.get("file") else {
            return Err(Error::IndexShape {
                path: path.to_owned(),
                message: "a dependencyMaps entry has no string `file`".to_owned(),
            });
        };
        let slice_path = root.join(file);
        let slice: JsonObject = read_json(&slice_path)?;
        let Some(Value::Object(declarations)) = slice.get("declarations") else {
            return Err(Error::IndexShape {
                path: slice_path,
                message: "declarations is not an object".to_owned(),
            });
        };
        for (name, module) in declarations {
            let module = match module {
                Value::String(module) => module.clone(),
                other => other.to_string(),
            };
            match out.iter_mut().find(|(other, _)| other == name) {
                Some(slot) => slot.1 = module,
                None => out.push((name.clone(), module)),
            }
        }
    }
    Ok(out)
}

/// One `index.json` module entry: the two fields this stage reads, plus the
/// object itself.
///
/// The **raw object is what goes back out**, key order and unknown keys
/// included: the merged index carries the extractor's entries verbatim, so a
/// typed struct here would quietly rewrite them into this crate's field order.
#[derive(Clone, Debug, PartialEq, Eq)]
struct IndexEntry {
    module: String,
    file: String,
    raw: Value,
}

/// `index.modules`, refused rather than guessed at when it is not an array of
/// objects each carrying `module` and `file` as strings.
///
/// The prototype would read `undefined` out of a malformed entry and write a
/// file called `undefined`; no extraction produces that, so it is a refusal.
fn index_entries(index: &JsonObject, path: &Path) -> Result<Vec<IndexEntry>, Error> {
    let shape = |message: &str| Error::IndexShape {
        path: path.to_owned(),
        message: message.to_owned(),
    };
    let Some(Value::Array(modules)) = index.get("modules") else {
        return Err(shape("modules is not an array"));
    };
    modules
        .iter()
        .map(|entry| {
            let string = |key: &str| match entry.get(key) {
                Some(Value::String(text)) => Ok(text.clone()),
                _ => Err(shape(&format!("an index entry has no string `{key}`"))),
            };
            Ok(IndexEntry {
                module: string("module")?,
                file: string("file")?,
                raw: entry.clone(),
            })
        })
        .collect()
}

/// `` `${value}` `` — how a template literal prints one of the four index
/// fields. A key that is not there prints `undefined`.
fn js_display(value: Option<&Value>) -> String {
    match value {
        None => "undefined".to_owned(),
        Some(Value::String(text)) => text.clone(),
        Some(other) => other.to_string(),
    }
}

fn read_json<T: serde::de::DeserializeOwned>(path: &Path) -> Result<T, Error> {
    let text = fs::read_to_string(path).map_err(|source| Error::Io {
        path: path.to_owned(),
        source,
    })?;
    serde_json::from_str(&text).map_err(|source| Error::Json {
        path: path.to_owned(),
        source,
    })
}

fn read(path: &Path) -> Result<Vec<u8>, Error> {
    fs::read(path).map_err(|source| Error::Io {
        path: path.to_owned(),
        source,
    })
}

fn copy(from: &Path, to: &Path) -> Result<(), Error> {
    fs::copy(from, to).map(|_| ()).map_err(|source| Error::Io {
        path: from.to_owned(),
        source,
    })
}
